### ISSUE TITLE
scene edit and merge

### ISSUE THREAD

**Issue by Bin-ze** [playcanvas/supersplat#102]
Great work!

I want to merge two scenes that were rebuilt separately.
Some operations include:

  Scale alignment
  Subscene rotation and translation
  Merge export

I want to implement it on supersplat, can you give me some advice?

**Comment by CiberNin** [comment]
Duplicate of [Issue 53](https://github.com/playcanvas/supersplat/issues/53)

**Comment by slimbuck** [comment]
Closing as above. BTW we're busy adding this feature, coming soon.
