### ISSUE TITLE
Move, Rotate, Scale on selections

### ISSUE THREAD

**Issue by 7Jaws9Eyes** [playcanvas/supersplat#109]
Are there plans to make the manipulations tools work on selections? ive been playing around with trying to implement it myself but i couldnt get it done. changing xyz coordinates in splatData seems not the way to go 😆

Creating a new asset from a selection and loading it along side the root asset seems like a huge hassle and has some issues with rendering where from some angles things can become invisble or rendered on the wrong plane when assets overlap.

**Comment by willeastcott** [comment]
Fixed by https://github.com/playcanvas/supersplat/pull/217
