### ISSUE TITLE
Brightness/saturation/contrast controls

### ISSUE THREAD

**Issue by hardikdava** [playcanvas/supersplat#112]
Hello, great work. Is it possible to change color of splat? if so then how can I modify properties of splatdata? Thanks

**Comment by slimbuck** [comment]
Hi @hardikdava ,

How would you like to change the color? Brightness/saturation/contrast controls or something else?

Thanks

**Comment by hardikdava** [comment]
hey @slimbuck, yeah I want something similar like Brightness/saturation/contrast controls.

**Comment by murcje** [comment]
whitebalance would be usefull too

**Comment by simonbethke** [comment]
I created a draft that allows to edit Brightness, Temperature and Tint at the moment. Saturation and Contrast would be nice too. I think this won't be hard to add... but at the moment I would like to know what the Product Owner thinks :)

**Comment by slimbuck** [comment]
Done in #267. This is implemented per scene right now, but we will extend this to per-splat in future.
