### ISSUE TITLE
Feature Request:  WASD model navigation

### ISSUE THREAD

**Issue by realstevewarner** [playcanvas/supersplat#115]
Just a quick request to allow for standard WASD keyboard shortcuts for camera movement throughout the scene.  These controls are standard in Unreal, TwinMotion, Blender, etc. and it would be very helpful to have them in Super Splat.  Also, we routinely do "fly by" animations so previewing how close the camera can get to an object without it getting blurry is very helpful.

Thanks for your consideration!

**Comment by slimbuck** [comment]
Hi @realstevewarner ,

Yes we are planning to add WASD fly controls.

For testing how close you can get to an object, try double-clicking the scene to set the camera focus point. Then you can zoom the camera in and out.

Thanks!
