### ISSUE TITLE
Is it possible to support 2DGS?

### ISSUE THREAD

**Issue by oUp2Uo** [playcanvas/supersplat#117]
https://github.com/hbb1/2d-gaussian-splatting

2DGS has smaller result file by filtering points and changing scale from 3 float to 2 float.
Usually, training using default parameters and the same images, 2DGS would have a result which is half of 3DGS's.
And the edge point of the object is more clear than 3DGS.

By manually change the 2DGS ply file to 3DGS ply file (add 3rd scale with small value like 0.00001), 
`supersplat` could be used to delete points.
But the preview is not correct.

Is it possible to support 2DGS, or where could I change the preview algorithm manually?

Thank you.

2DGS (add 3rd scale):
![2dgs](https://github.com/playcanvas/supersplat/assets/29222415/0d74c9ec-b6b2-40a2-ab84-c794d57c56f6)
3DGS:
![3dgs](https://github.com/playcanvas/supersplat/assets/29222415/f75ac75e-c865-4609-97d8-8148e21cbcf4)

**Comment by slimbuck** [comment]
Hi @oUp2Uo , can you provide an example 2dgs file? Thanks!

**Comment by oUp2Uo** [comment]
Thanks for the reply.

2DGS ply has almost the same format as 3DGS.
The difference is that the header do not have `property float scale_2`.

Here is one simple example I have trained and then edited as I said.

![2024-06-25 191248](https://github.com/playcanvas/supersplat/assets/29222415/eac4d821-27ce-4fd5-a906-f443036af730)

[point_cloud.zip](https://github.com/user-attachments/files/15969156/point_cloud.zip)

**Comment by slimbuck** [comment]
I tried adding `scale_2` with 0's to this model at load time, but it doesn't work.

I created an issue on the original repo [here](https://github.com/hbb1/2d-gaussian-splatting/issues/94). Perhaps the original authors can help.

**Comment by slimbuck** [comment]
I'd forgotten PLY stores log(scale). Here is your model in SS with the simple loading change:

<img width="1448" alt="Screenshot 2024-06-25 at 12 27 22" src="https://github.com/playcanvas/supersplat/assets/11276292/29b1f806-29b4-43f7-b441-43d842248f20">

**Comment by slimbuck** [comment]
If you want to do this yourself make sure `scale_2` is filled with `Math.log(1e-06)` or similar.

We could also add support for adding the missing `scale_2` on load, but then we'd probably need to remove `scale_2` on saving.

**Comment by Yuhuoo** [comment]
Can u share your code? I can see nothing when I test the point cloud

> Thanks for the reply.
> 
> 2DGS ply has almost the same format as 3DGS. The difference is that the header do not have `property float scale_2`.
> 
> Here is one simple example I have trained and then edited as I said. Could not have the correct preview, so the result has many noises.
> 
> ![2024-06-25 191248](https://private-user-images.githubusercontent.com/29222415/342683510-eac4d821-27ce-4fd5-a906-f443036af730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mzg3OTgsIm5iZiI6MTcxOTkzODQ5OCwicGF0aCI6Ii8yOTIyMjQxNS8zNDI2ODM1MTAtZWFjNGQ4MjEtMjdjZS00ZmQ1LWE5MDYtZjQ0MzAzNmFmNzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE2NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTJkNDhiMjIwMTdiZjUxODk1MjY3NjA3OTNiZGE0MWZjYWU4NmQ5OTgzOGQxM2VmNTIxYTE2NTNkMTQ5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uGHxyc1HzBQsTk2PzdePwfQ8f3QHTnjm5rXY4FBBuzA)
> 
> [point_cloud.zip](https://github.com/user-attachments/files/15969156/point_cloud.zip)

<img width="1573" alt="image" src="https://github.com/playcanvas/supersplat/assets/91204817/c8f9ac18-d97b-4ff4-b26a-6707fed723ec">

**Comment by Yuhuoo** [comment]
I don't understand how to modify the code.
<img width="1224" alt="image" src="https://github.com/playcanvas/supersplat/assets/91204817/79b85a59-d908-44d5-83f6-e19541479b6b">
