### ISSUE TITLE
bug： Cropping without depth testing

### ISSUE THREAD

**Issue by Bin-ze** [playcanvas/supersplat#118]
When cropping the scene, not only the gs points in front of the camera are cropped, but also the gs points behind the camera. This is unreasonable, so I think it is necessary to add depth judgment and crop the point cloud in front of the camera.

**Comment by slimbuck** [comment]
Hi @Bin-ze ,

Oh my gosh - this is a bug!

Will fix ASAP, thanks for reporting.

**Comment by Bin-ze** [comment]
@slimbuck  I want to know when the web version will be updated？ 

https://playcanvas.com/supersplat/editor : There is still a problem with the Gaussian after cropping the camera

**Comment by willeastcott** [comment]
@Bin-ze SuperSplat should be updated early next week.
