### ISSUE TITLE
Support for 2d gs scenes

### ISSUE THREAD

**Issue by Yuhuoo** [playcanvas/supersplat#121]
Thanks for your nice work. I would like to ask how can I use this project to edit the ply file of 2D GS. After I imported the project, no target was rendered.

<img width="1245" alt="image" src="https://github.com/playcanvas/supersplat/assets/91204817/32142191-f770-4ce0-b645-8f2fc84406a0">

**Comment by slimbuck** [comment]
We must add loading support for 2d GS. It's a tiny change so hopefully we'll add it soon.

**Comment by slimbuck** [comment]
I've added very simple 2d loading support.
