### ISSUE TITLE
Add deletion of scenes from the SCENE panel

### ISSUE THREAD

**Issue by Shadow-line** [playcanvas/supersplat#122]
I found that the new version can load multiple gs models, but after I put multiple models into the scene, I can't delete a model I don't want. What should I do?

**Comment by slimbuck** [comment]
Hi @Shadow-line , we'll add the delete option soon. Sorry for the trouble!

**Comment by slimbuck** [comment]
This was fixed in #126 (v0.22.0). This update will be published soon.
