### ISSUE TITLE
rollup-plugin-sass 1.13.1 cause rollup fail on windows

### ISSUE THREAD

**Issue by jiangheng90** [playcanvas/supersplat#124]
app version：0.21.0
node version：v20.15.0
npm version: 10.8.1
os: win11 23h2
ms edge: 126.0.2592.87
chrome:  126.0.6478.127
 I have test both  1.13.1 and  1.13.0 ,the commite last night will cause import scss url error
```
[1]  INFO  Accepting connections at http://localhost:3000
[0] rollup v4.18.0
[0] bundles src/index.ts → dist...
[0] (!) Unresolved dependencies
[0] https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
[0] D:Repossuper-splat
ollup-plugin-sassdist/insertStyle.js (imported by "src/style.scss")
[0] created dist in 5.7s
[0] bundles src/sw.ts → dist...
[0] created dist in 607ms
```
in browser it will be
```
Not allowed to load local resource: file:///D:/Repossupersplatode_modulesollup-plugin-sassdist/insertStyle.js
```

**Comment by slimbuck** [comment]
Thanks for reporting @jiangheng90 - we'll investigate today

**Comment by jiangheng90** [comment]
https://github.com/elycruz/rollup-plugin-sass/pull/139/files 
I think in this issue, they have change the config. u can have a look

**Comment by TonyDua** [comment]
@slimbuck Sorry,but this problem still exists in version 0.22.
`localhost/:1 Not allowed to load local resource: file:///C:/supersplatode_modulesollup-plugin-sassdist/insertStyle.js`

**Comment by slimbuck** [comment]
Hi @TonyDua , sorry I don't have access to a windows machine so wasn't able to investigate. I might get a chance to revert the updates sass rollup plugin version today.

**Comment by TonyDua** [comment]
@slimbuck  Thanks, can't wait to see how this issue progresses. If you need a hand with anything, I'm more than happy to help out.
