### ISSUE TITLE
How to develop locally

### ISSUE THREAD

**Issue by chaoyang915506** [playcanvas/supersplat#132]
Hello, White ask some questions. After I pull down the dev code, load the dependency, and use npm run develop to start the project. After I modify the file, the dis directory file will also change, but the content of the page will not change, nor will the restart. May I ask what configuration I need before I can formally develop?

**Comment by slimbuck** [comment]
Hi @chaoyang915506 ,

You must make sure the service worker is reloaded when developing.

In chrome, ensure the option is enabled in the developer console under application->service worker (I forget the name now).

In safari make sure to enable developer options and clear the browser cache when reloading (Ctrl+command+e on my maxjone

**Comment by chaoyang915506** [comment]
Thanks for solving my problem

**Comment by chaoyang915506** [comment]
Thanks for solving my problem
