### ISSUE TITLE
[Feature Request] Set object origin

### ISSUE THREAD

**Issue by equilento** [playcanvas/supersplat#140]
Sometimes models origin is way off and it would be awesome if we could change it.

**Comment by slimbuck** [comment]
Hi @equilento,

I actually merged a [PR](#137) yesterday which sets the pivot location when you double click on the splat while one of the transform tools are active.

I imagine we will eventually add a "pivot" edit mode which allows you to set the placement arbitrarily (using the gizmo), but I hope this quick fix will tide us over till then.

We'll hopefully release this update on Monday and I'd love to hear if this helps!

**Comment by equilento** [comment]
I tried double clicking but it just positions the camera to clicked point. I can wait till Monday :D 
Thank you!
