### ISSUE TITLE
Manipulate splat positions

### ISSUE THREAD

**Issue by llamaj13** [playcanvas/supersplat#148]
Moving splats would be a huge help. A soft select style adjustment with position/scale/rotate would be ideal. A lattice style manipulator would also work wonders.

**Comment by OrangeSodahub** [comment]
@llamaj13 Hi, I have the same question, did you figure that out?

**Comment by slimbuck** [comment]
It is currently not possible to manipulate a subset of splats, but we'll hopefully add support for this soon.

**Comment by slimbuck** [comment]
Done in #217
