### ISSUE TITLE
I'm having permission issues trying to deploy to electron

### ISSUE THREAD

**Issue by chaoyang915506** [playcanvas/supersplat#152]
![image](https://github.com/user-attachments/assets/7b6255d2-41a3-4356-ba8e-06fd4c6be0a2)
When I deployed the ply file to electron, this error was displayed when I exported the PLY file that had been trimmed. Is there any way to solve the problem of export or save as failure

**Comment by slimbuck** [comment]
What is the actual error message? (This screenshot shows where is the error originates).

**Comment by chaoyang915506** [comment]
![image](https://github.com/user-attachments/assets/9f4ae5ad-6858-41d6-b777-b34e643fa4a7)
![image](https://github.com/user-attachments/assets/75e53ec6-01af-453d-91a4-ff46c61d809c)

This is the console error, I search this error solution is to add configuration to electron to allow the loading of local resources, I try to add also has no effect, guess may be electron browser does not support some methods of window

**Comment by slimbuck** [comment]
Ok interesting.

I haven't tried running SS as a native app yet. I can't investigate this right now, because we're in the middle of a large UI update, but afterwards I may have time to investigate.

It would be great to get this working though, so if you find anything out, please share with us!
