### ISSUE TITLE
What is the appropriate way to set initial camera position of scene? 

### ISSUE THREAD

**Issue by nerpa87** [playcanvas/supersplat#153]
Hello, thanks for sharing great viewer. Is there any way to set initial camera position? Gaussian splatting implementations usually produce cameras.json file with cameras positions as rotation matrices and translation vectors, I would like to use it to set up initial camera position, how can I do it? Thanks

**Comment by slimbuck** [comment]
I am keen to add a `cameras.json` loader which would populate a list of camera poses for the user to select from. Choosing a pose would snap the camera to the pose.

If you're keen on trying this yourself, you could update https://github.com/playcanvas/supersplat/blob/main/src/file-handler.ts#L112 to support `cameras.json` by extracting the first camera pose and then do something like:
```javascript
const camera = scene.camera;
camera.setFocalPoint(...)
camera.setAzimElev(...)
```

**Comment by nerpa87** [comment]
Thank you for fast answer, that is what I was trying to do.  Can you please explain meaning of `setFocalPoint` parameter? The focal point is the point that camera looks at? And what is `distance` from `setDistance` method of camera class?

**Comment by slimbuck** [comment]
> The focal point is the point that camera looks at?

Yes, camera has:
* A focal point around which it orbits
* A distance which determines how far away the camera is from the focal point
* Azimuth and elevation specify the orientation of the camera

Use `setFocalPoint`, `setAzimElev` and `setDistance` to modify any of these. The camera will smoothly transition to the target placement.

**Comment by slimbuck** [comment]
Closing, but please reopen if you have more questions!
