### ISSUE TITLE
Camera shifts when toggling Settings

### ISSUE THREAD

**Issue by marklundin** [playcanvas/supersplat#156]
When toggling the Settings icon quickly, it will sometimes be picked up by the camera controller and will shift the camera

https://github.com/user-attachments/assets/b83c4222-ac95-45d5-b0a1-360bb5288560

**Comment by slimbuck** [comment]
Ahh yes the venerable double click! Thanks so much!

**Comment by slimbuck** [comment]
Fixed in #155
