### ISSUE TITLE
Export 'missing header'

### ISSUE THREAD

**Issue by aliciagong** [playcanvas/supersplat#158]
Thank you so much for developing this!! It's a lot easier to manipulate than the aescripts plug-in and UE one in terms of cleaning smaller more detailed scans. 

Question: Once I exported the scene with the 'export' function, neither CloudCompare nor Meshlab recognizes the file because it's missing the ply header. I've opened the exported scene in VSCode and no readable header is present. Am I doing something wrong with the export feature? How do I correctly export the scene or is there a developmental issue? 

*btw if anyone knows how I can convert gs .ply files to more stable 3D formats it'll be greatly appreciated. I tried many different softwares and plug-ins, they either don't recognize the color data or they only allow the file to be exported back to the same format.

**Comment by slimbuck** [comment]
Hi @aliciagong ,

Please use Scene -> Save option rather than Export. Save option will write out an uncompressed PLY. Export writes out compressed PLY files.

**Comment by slimbuck** [comment]
Closing the issue, but please reopen it if you need anything else.
