### ISSUE TITLE
Splat rendering is different from Postshots ADC

### ISSUE THREAD

**Issue by equilento** [playcanvas/supersplat#159]
I have a difficulty understanding why GS looks different (much better IMO) when after development viewed inside PostShot. When exported to SuperSplat they lose intricate details that makes them photorealistic.
Examples:
![Screenshot 2024-08-08 202619](https://github.com/user-attachments/assets/c3f6588e-d8e5-49b6-82a3-4840375a8d1b)
![Screenshot 2024-08-08 202647](https://github.com/user-attachments/assets/57eb610d-0307-420a-b77d-d7af05ead87c)
![Screenshot 2024-08-09 120439](https://github.com/user-attachments/assets/131c26f6-5cb5-4b33-acd1-c8b127ac200a)
![Screenshot 2024-08-09 120450](https://github.com/user-attachments/assets/3f3033a5-f0c8-4cc4-b44c-e4b24dc576ab)

**Comment by slimbuck** [comment]
Wow these captures look incredible.

I can think of two possible reasons:
* we don't render using spherical harmonics. this will result in fewer reflections and less overall scene contrast.
* we don't render splats that are very small on screen (2 pixels across) to speed up rendering. this may be why some tiny details aren't being rendered.

I would be keen to make both of these optional in SuperSplat and actually, thinking about it some more we _must_ stop the 
pixel-size rendering optimisation anyway.

If you are able to provide me with an example file I can investigate further and confirm my suspicions above.

Thanks!

**Comment by equilento** [comment]
Wow did you really just reply in 9 minutes! Thanks, I've been working on GS since the start and captures are now ready for clients, all I need now is to have this matching quality :)
https://drive.google.com/drive/folders/1-uQc19U0zl2vRJgXmjbpRUcMTDXOLkDu?usp=sharing

P.S. You probably have no idea how much you've been of help, I hope to give back to this community in some way.

**Comment by slimbuck** [comment]
So I can confirm that the quality difference is due to not rendering with spherical harmonic data:

<img width="2056" alt="Screenshot 2024-08-12 at 13 44 40" src="https://github.com/user-attachments/assets/a816ecc7-7194-496e-b1c5-03e432458a3d">

<img width="2056" alt="Screenshot 2024-08-12 at 13 44 43" src="https://github.com/user-attachments/assets/29d5a8c0-7124-47e6-a4c4-82cc07e05567">

I will probably add an option to render with spherical harmonics in Supersplat, however it will be quite a lot slower and probably not ideal for most users.

Can I just ask what software did you use to generate this scene? If you're able to, I would love to see a version generated without SH data.

**Comment by equilento** [comment]
Spherical harmonics as an option would be great. I used Postshot.
https://drive.google.com/file/d/12gdglMBWHt96Hceru-lKor3PPiRYwwhR/view?usp=drive_link

**Comment by slimbuck** [comment]
@equilento - do you mind if I use the face comparison screenshot to show the new SH rendering support in Supersplat?

**Comment by equilento** [comment]
I've asked the model and he wonders what it'll be used for and said he's fine with it as long as its not being used commercialy and in front of millions of people, so I don't know what to tell you. Go for it I guess. Maybe some royalties if his face gets famous because of this? 😅

**Comment by slimbuck** [comment]
This is now release @equilento. Thank you for raising this issue and providing the example scenes!!

https://github.com/playcanvas/supersplat/releases/tag/v1.2.0

**Comment by equilento** [comment]
Glad to be of help. Btw I think I've found some bugs already regarding SH, I'll post them tonight.

**Comment by slimbuck** [comment]
> Btw I think I've found some bugs already regarding SH, I'll post them tonight.

Impossible! Um... I mean, please do - I look forward to it :D

**Comment by slimbuck** [comment]
Hi @equilento ,

This is another great model, thanks!

It just so happens I was doing some investigation with postshot myself and seems postshot doesn't export PLY files correctly.

I logged a bug on their discord https://discord.com/channels/1177235109162799105/1275445713836310700.

You should be able to confirm this yourself by importing the ply back into postshot. It should look similar to Supersplat.

I am away for a few days so can't test it myself on your example, but you should be able to work around this issue for now by zeroing out the scene rotation in postshot before exporting it to PLY.

I have found Supersplat has a slight SH discoloration in some cases which I will investigate when I'm back.

Thanks!

**Comment by willeastcott** [comment]
@slimbuck Could this have anything to do with the anitialias + device pixel ratio settings selected by SuperSplat?
