### ISSUE TITLE
Camera sensitivity on mobile

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/supersplat#16]
The sensitivity of the camera movement on mobile phone is too low. I am speaking of the two fingers control to move the camera sideways or up/down.

https://github.com/playcanvas/super-splat/assets/5677782/556b409e-4c1d-478b-a110-114f7282a8b4

**Comment by willeastcott** [comment]
This appears to be fixed now. Closing.

https://github.com/user-attachments/assets/01d1dee7-5b6c-4bf8-95ee-4db4f23308ed
