### ISSUE TITLE
Exporting the indices of deleted splats

### ISSUE THREAD

**Issue by JiamingSuen** [playcanvas/supersplat#162]
Hi there, thanks for this amazing tool!

I'm writing a feature to export the vertex indices of the deleted splats (in the original ply) during editing. I tried to implement this at 63f99d01a7a18cd7df8f1adba08c247574063412 and everything worked well. When I try the same thing with the current HEAD (v1.0.0), the vertex indices order seems to have changed during loading (or other processing steps). Am I doing anything wrong? Could the vertex order be changed back? 

This is how I'm implementing this feature:

In `splat-convert.ts` I wrote a function similar to `convertPly()`, only exporting the splat index with `.deleted` state:
```js
const exportDetetedIndices = (convertData: ConvertEntry[]) => {
    // count the number of deleted splats
    const totalSplats = countTotalDeletedSplats(convertData);

    // get the vertex properties common to all splats
    const propNames = ['orig_index'];

    const headerText = [
        `ply`,
        `format binary_little_endian 1.0`,
        `element vertex ${totalSplats}`,
         propNames.map(p => `property float ${p}`),
         `end_header`,
         ``
    ].flat().join('\n');

    const header = (new TextEncoder()).encode(headerText);
    const result = new Uint8Array(header.byteLength + totalSplats * propNames.length * 4);
    const dataView = new DataView(result.buffer);

    result.set(header);

    let offset = header.byteLength;

    for (let e = 0; e < convertData.length; ++e) {
        const entry = convertData[e];
        const splatData = entry.splatData;
        const state = splatData.getProp('state') as Uint8Array;

        for (let i = 0; i < splatData.numSplats; ++i) {
            // only concerned with deleted splats
            if ((state[i] & State.deleted) !== State.deleted) continue;

            // write
            for (let j = 0; j < propNames.length; ++j) {
                dataView.setFloat32(offset, i, true);
                offset += 4;
            }
        }
    }

    return result;
    
    
};

const countTotalDeletedSplats = (convertData: ConvertEntry[]) => {
    return convertData.reduce((total, entry) => {
        const splatData = entry.splatData;
        const state = splatData.getProp('state') as Uint8Array;
        for (let i = 0; i < splatData.numSplats; ++i) {
            total += (state[i] & State.deleted) === State.deleted ? 1 : 0;
        }
        return total;
    }, 0);
};

```
To provide some visualizations, these are the splats I want to remove:
<img width="816" alt="Screenshot 2024-08-12 at 11 09 08 PM" src="https://github.com/user-attachments/assets/97372116-6953-4a0c-930e-ab836e9d1301">

And by exporting the deleted indices and removing them with another python script, here are the remaining splats:
<img width="929" alt="Screenshot 2024-08-12 at 11 10 07 PM" src="https://github.com/user-attachments/assets/35587213-f973-4185-840e-76ec9accbc50">

Clearly the removed splats are not what have been selected in the beginning.

Any help would be appreciated!

**Comment by slimbuck** [comment]
Hi @JiamingSuen,

We updated our splat rendering to re-order data at load time for optimal rendering performance in [this PR](https://github.com/playcanvas/engine/pull/6357).

You can disable this though in Supersplat, by adding a `reorder: false` option to [this line](https://github.com/playcanvas/supersplat/blob/main/src/asset-loader.ts#L51).

Thanks!

**Comment by slimbuck** [comment]
(And just so you know, reordering the splat training data speeds up rendering by a huge amount - 4x in some cases for large scenes on a Mac M1. So you might find scenes run slowly after making this change).

**Comment by slimbuck** [comment]
Closing, but please reopen if you have any more questions.
