### ISSUE TITLE
[Feature Request] Implementation of mip-splatting rasterizer

### ISSUE THREAD

**Issue by walsvid** [playcanvas/supersplat#163]
Thank you for providing the supersplat tool! It's been very helpful. 

I have a question regarding future development plans: Do you have any plans to implement a mip-splatting rasterizer, similar to the modifications made to the original Gaussian Splatting renderer?

If you're open to contributions from the open-source community to help with this implementation, could you please provide some guidance on which parts of the code would need to be modified to achieve an effect similar to the `diff-gaussian-rasterization` forward in Gaussian Splatting?

Thank you for your time and consideration!

**Comment by slimbuck** [comment]
Hi @walsvid ,

We will implement GS rendering using compute shaders at some point in the future (we currently only use vertex and fragment shaders) at which point we could consider adding mip-splatting.

This probably won't happen in the near future though.

Thanks!

**Comment by walsvid** [comment]
Thank you for your reply, and look forward to seeing SuperSplat add this feature in the future. I'll close this issue for now.
