### ISSUE TITLE
How to use the old version?

### ISSUE THREAD

**Issue by Lizhinwafu** [playcanvas/supersplat#164]
I can't find the old version link.

**Comment by slimbuck** [comment]
Hi @Lizhinwafu ,

May I ask why you are after an old version?

The latest Supersplat v1.0 has the same functionality as before, but with (hopefully) a better UI.

To get an earlier version you must run it locally using git and npm:
```
git clone https://github.com/playcanvas/supersplat.git
cd supersplat
git checkout v0.25.2
npm i
npm run develop
```
After doing this you can access the local version by navigating to `http://localhost:3000` in your browser.

Thanks!

**Comment by slimbuck** [comment]
Oh, interesting.

The white lines show the bounding box of the selected splat. (In some cases this is the only way you'll know which splat is selected in the SCENE MANAGER panel).

We could add an option to hide these if necessary?

**Comment by slimbuck** [comment]
You can't currently, but it's another option we will add very soon.

You should be able to select the background color and color of the centers (not just blue).

**Comment by slimbuck** [comment]
Ok @Lizhinwafu , that makes sense.

I will add an option to hide the bounding box (and perhaps the background color).

**Comment by slimbuck** [comment]
This is now deployed @Lizhinwafu, please give it a go.

You'll find the toggle on the view panel:

<img width="441" alt="Screenshot 2024-08-15 at 09 26 18" src="https://github.com/user-attachments/assets/67f4b25d-9ee4-4b6a-b9be-b849c2ba3be9">
