### ISSUE TITLE
Hide Panels?

### ISSUE THREAD

**Issue by fasteinke** [playcanvas/supersplat#168]
Minor request ... would it be possible to move the command panels "out of the way", or roll them up, etc - for clear viewing of model? If this is already possible, I apologise for asking ...

Frank

**Comment by slimbuck** [comment]
Hi @fasteinke ,

Collapsible panels were actually part of the original design. We'll definitely add them soon as we can!

**Comment by slimbuck** [comment]
Fixed in #183
