### ISSUE TITLE
Error: Not allowed to load local resource when using rollup-plugin-sass

### ISSUE THREAD

**Issue by action9981** [playcanvas/supersplat#171]
错误信息：
Not allowed to load local resource: file:///D:/workeserverplyloadersupersplatode_modulesollup-plugin-sassdist/insertStyle.js  
重现步骤：
github clone 1.2.0，
nvm use 18.12.0，
cd project，
npm i，
win10 edge、google chrome，访问 http://localhost:3000,就报这个错，从1.0.0 开始报错的。前面版本不报错。
我的目的是想去掉高斯那些椭圆

**Comment by slimbuck** [comment]
Hi @action9981 ,

I just tried this myself from a clean install on windows and it worked fine.

This error looks like an issue from v1.1. Could it be your browser cache still using an old version of application?

Please can you try enabling `application->service workers->update on reload` and `bypass for network` and then reload?

![edge](https://github.com/user-attachments/assets/105ccebd-f85a-4aca-9dac-36dd3e6056f8)

Thanks!

**Comment by action9981** [comment]
"Thank you for your response. I've followed your instructions, but it still doesn't work. Versions greater than 1.0.0 don't work either. My Node version is 18.20.2."

**Comment by action9981** [comment]
@slimbuck Great, it can be used now

**Comment by slimbuck** [comment]
👍🏻🎉
