### ISSUE TITLE
How to integrate with Vue

### ISSUE THREAD

**Issue by action9981** [playcanvas/supersplat#177]
I want to integrate PlayCanvas into my own Vue project. How can I use it, and are there any relevant examples? The goal is to load and edit Gaussian models.

**Comment by willeastcott** [comment]
Does this help?

https://forum.playcanvas.com/t/playcanvas-and-vue-js/15560

**Comment by slimbuck** [comment]
Sorry @action9981 we're not Vue specialists.

It might be worth asking on their community.

If we can help with anything on Supersplat, please let us know!
