### ISSUE TITLE
Visualize .splat file

### ISSUE THREAD

**Issue by Deaddawn** [playcanvas/supersplat#181]
Hello, wondering is there a way we can visualize a .splat file which can be saved as a format

**Comment by slimbuck** [comment]
Hi @Deaddawn,

No you can't currently load .splat format. Shouldn't be too difficult to add.

Thanks

**Comment by willeastcott** [comment]
If we _do_ add this, I would suggest this lives under the Import menu (versus Open).

**Comment by simonbethke** [comment]
Actually not only this should be an import. Ply isn't the supersplat format either. If you load two ply-files, save and reopen them, you end up with one merged file.
What it actually needs is import and export for ply and splat files and additionally some kind of supersplat file that also contains a scenegraph and poses.

**Comment by simonbethke** [comment]
I might look into implementing this tomorrow

**Comment by simonbethke** [comment]
In https://github.com/playcanvas/supersplat/pull/209 I implemented basic splat import

**Comment by Deaddawn** [comment]
> In #209 I implemented basic splat import

Wonderful! Thanks a lot!

**Comment by slimbuck** [comment]
Done in #218
