### ISSUE TITLE
How i can change the pivot point?

### ISSUE THREAD

**Issue by trunganhvux** [playcanvas/supersplat#182]
Like the title, when i watched some youtube video on old version you can change the pivot point
But i can't find it anywhere on v1.2.3

Hope someone can help me, thanks.

**Comment by slimbuck** [comment]
Hello! Have you tried enabling one of the transformer gizmos (translate, rotate, scale) and double clicking somewhere on the scene?

**Comment by trunganhvux** [comment]
> Hello! Have you tried enabling one of the transformer gizmos (translate, rotate, scale) and double clicking somewhere on the scene?

ah seem like it, but double click are not really accurate but i think i have to deal with it for now
