### ISSUE TITLE
Is it possible to add the "add camera model" function?

### ISSUE THREAD

**Issue by seulqxq** [playcanvas/supersplat#186]
Hello, is it possible to add the "add camera model" function?

**Comment by slimbuck** [comment]
Hi @seulqxq , can you explain a little more what the feature is? Thanks!

**Comment by seulqxq** [comment]
Thank you for your quick response!
The camera model is similar to that described in the figure, using the "Vuer" visualization tool.
Using this camera model, we observed objects and saved images based on various camera poses. However, the resulting visualization quality is not satisfactory and does not match our expectations.
![image](https://github.com/user-attachments/assets/8fba6859-6c49-45a7-b615-cf182f4d0c9f)

**Comment by slimbuck** [comment]
Hi @seulqxq ,

Sorry but I'm still not sure exactly what you're asking for.

Do you want the ability to load a cameras.json (camera poses) file? Or the ability to take high resolution screenshots? Or something else?

Thanks

**Comment by seulqxq** [comment]
Thanks for your reply@slimbuck,

Yes, we want to import a camera.json file. Then, the camera model will be moved, and the view under the camera model will be visualized, instead of moving the entire scene.

Thanks

**Comment by slimbuck** [comment]
Ahh ok. I actually already have a simple version of this which I could resurrect.

**Comment by seulqxq** [comment]
Wow, I'm very looking forward to the update !

**Comment by slimbuck** [comment]
Would this be enough?

Loading a `cameras.json` file adds to a list of camera poses in the view panel:

https://github.com/user-attachments/assets/db779412-5284-4f77-b166-4270f5d3437d

Click a pose to set the camera.

**Comment by seulqxq** [comment]
Wow, It looks great, looking forward to its launch and can't wait to try it out!

**Comment by willeastcott** [comment]
@slimbuck You might want to run this by Greg - it does kind of muddy the meaning of the VIEW OPTIONS panel.

**Comment by Unimendacity** [comment]
Stunning work!
Could you please clarify if the camera FOV is horizontal, vertical, or diagonal? 
Additionally, is there an API for customizing camera poses and obtaining simulated images of the 3D Gaussian splats from the camera's perspective?

**Comment by slimbuck** [comment]
Hi @Unimendacity,

The Field of View slider in the VIEW OPTIONS panel sets the FOV for the largest canvas dimension of the camera (either vertical or horizontal). On mobile this will be likely be vertical and on desktop usually horizontal.

There is currently no API for camera poses, but I'm interested to know what you mean. Would you like the ability to take screenshots of the camera poses automatically, or something different?

Thanks!

**Comment by Unimendacity** [comment]
Thank you for your response!
Would it be possible to control the camera pose by directly specifying values for position and rotation, rather than using cameras.json?
Additionally, could we obtain an image of the 3D Gaussian splats from the current camera view, similar to a screenshot of the current page without the toolbar?
