### ISSUE TITLE
Can not  select file when viewing a large number of files. There is no scroll wheel in the sidebar.

### ISSUE THREAD

**Issue by TxT1212** [playcanvas/supersplat#187]
![image](https://github.com/user-attachments/assets/cd1121e8-0e58-4ff1-a209-ec144bb74657)
I remember previous version has one. Can it be added back?

**Comment by slimbuck** [comment]
Oh, yes! Sorry about that. Will release a fix today.

**Comment by slimbuck** [comment]
This fix is now available, thanks!
