### ISSUE TITLE
Can not import large size compressed ply 

### ISSUE THREAD

**Issue by cloudending** [playcanvas/supersplat#189]
the compressed ply is exported from supersplat. But there are some error  when I  try to import it.
![image](https://github.com/user-attachments/assets/a6fa9f46-77f9-4020-b3f8-4abfc6e6ab65)

Small size ply is imported successfully. But large size ply is failed.
small ply: 24.1m
large ply: 119m

**Comment by slimbuck** [comment]
Hi @cloudending ,

I am able to load 1.5GB PLY files just fine.

Are you able to send me the PLY please so I can take a look?

Thanks!

**Comment by cloudending** [comment]
> Hi @cloudending ,
> 
> I am able to load 1.5GB PLY files just fine.
> 
> Are you able to send me the PLY please so I can take a look?
> 
> Thanks!
download link：https://we.tl/t-9IDsS7KYHN，it is a simplied ply which only contains " x y z f_dc_0 f_dc_1 f_dc_2 opacity scale_0 scale_1 scale_2 rot_0 rot_1 rot_2 rot_3". 
I try to export compressed ply from a full parameters ply which size is 2.23G. It can be imported successfully.

**Comment by slimbuck** [comment]
Thanks @cloudending! I can confirm the same issue on my side. Loading the compressed file into [model viewer](playcanvas.com/model-viewer) works fine though, so it's a bug in SuperSplat.

**Comment by slimbuck** [comment]
Looks like the PLY contains splats with scale of `-Infinity`, which isn't being handled very well.

**Comment by willeastcott** [comment]
It makes me wonder whether some kind of PLY linter might be cool to have in SuperSplat? Or maybe a log window that outputs problems found in loaded scenes.

**Comment by cloudending** [comment]
> While I fix this issue on my end @cloudendin, I found a workaround you can use to get this to working.
> 
> The splats causing the issue are all centered at (0, 0, 0).
> 
> You can see this and then delete them as follows:
> 
> 1. Open the SPLAT DATA panel
> 2. Choose `Distance` dropdown option, you will see there are 11k 0-size splats at the very center of the scene.
> 3. Select all these splats by clicking on the bar in the SPLAT DATA panel
> 4. Delete them
> 
> You can now export compressed without problem.
> 
> <img alt="Screenshot 2024-09-19 at 14 27 26" width="1636" src="https://private-user-images.githubusercontent.com/11276292/369016048-a3c4acec-2674-4d5f-941d-dd235602f476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzEwNzQsIm5iZiI6MTcyNzIzMDc3NCwicGF0aCI6Ii8xMTI3NjI5Mi8zNjkwMTYwNDgtYTNjNGFjZWMtMjY3NC00ZDVmLTk0MWQtZGQyMzU2MDJmNDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDAyMTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjk3YTg1MTQ4YTg3N2YxNzk5MTk0YzEyNTQ3NzE0NWNiODc4MjkxNDc4NmJiOGEzZDNkZDExMjRkYjZjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N6F19OcShU1ZsaXnDH44ngMjcNDDcCkricn7FnaKBHw">

it works. thanks for your working
