### ISSUE TITLE
A new  floor grid

### ISSUE THREAD

**Issue by nmgyaoyuan** [playcanvas/supersplat#190]
I  conference  webglstudio , coding  a new floor grid.  
I have forked from supersplat , and build a new project ( changed  much  codes，can not  push the codes only about the floor grid  ）
if u like the new floor grid , I like share the source code an resources。

![c5bbde6cebd2103a19e0ebfa30e61a5](https://github.com/user-attachments/assets/7bcdb7c3-6e17-459c-aac2-16a60d6b3fd1)

**Comment by slimbuck** [comment]
Hi @nmgyaoyuan ,

The grid looks awesome. I was wanting to do something similar myself. Please share so we can get it merged.

I see you've added some other tools too. If you'd like to get those merged in that's also be great.

Thanks!

**Comment by nmgyaoyuan** [comment]
@slimbuck   OK, i will push the codes about the grid .  

Sorry, the other features are currently unavailable as they are for commercial use. I may gradually make them available later.
