### ISSUE TITLE
Code for picker select function

### ISSUE THREAD

**Issue by Deaddawn** [playcanvas/supersplat#197]
Hi, there. Thank you for this useful splat tools for us! I am new to typescript code. Is it possible to point where is the code for "Picker Select". I plan to develop things based on this. Thanks again.

**Comment by slimbuck** [comment]
Hi @Deaddawn ,

The code for picker/rect select is in https://github.com/playcanvas/supersplat/blob/main/src/tools/rect-selection.ts

Thanks!
