### ISSUE TITLE
New 1.5.1 grid has unpleasant aliasing effect?

### ISSUE THREAD

**Issue by ferrouswheel** [playcanvas/supersplat#200]
![image](https://github.com/user-attachments/assets/4ced5492-2365-4643-b2f9-8970eac5428e)

**Comment by willeastcott** [comment]
What OS and browser are you using?

**Comment by willeastcott** [comment]
How it looks on iOS:

![image](https://github.com/user-attachments/assets/c8fc0464-b4a6-4207-ae0a-31f8f625b5d2)

**Comment by ferrouswheel** [comment]
Chrome version 127.0.6533.99 (Official Build) (64-bit)
Linux

(noticed after upgrade from version 1.2)

**Comment by slimbuck** [comment]
I know of some distant aliasing, but it's relatively subtle.

From your screenshot it looks like a possible shader issue. Perhaps something to do with alpha or ddx calc. Could you please post a screenshot here of the full grid?

Thanks!

**Comment by slimbuck** [comment]
I've managed to reproduce on Windows running Chrome.

**Comment by slimbuck** [comment]
The fix has been deployed, please give it a try now :)

Thanks so much for reporting this bug!!
