### ISSUE TITLE
Discord link issue

### ISSUE THREAD

**Issue by simonbethke** [playcanvas/supersplat#202]
I would really like to understand more how this supersplat is developed and if everybody can contribute or chat with the devs. For that I wanted to join the discord server, but the discord link from the help menu brings me to the server without any channels being accessible. Is that intended?

**Comment by slimbuck** [comment]
Hmm no I just tried and *_it worked for me_*. Not sure what the issue might be.

**Comment by simonbethke** [comment]
For me it opens like this:
![image](https://github.com/user-attachments/assets/45d71d2c-ccde-4cd3-9160-d225e3b499ea)

**Comment by slimbuck** [comment]
Does this invite link work? https://discord.gg/8GjzV4Tg

**Comment by simonbethke** [comment]
Yes, it does

**Comment by willeastcott** [comment]
Maybe you have to have previously joined the PlayCanvas DIscord server for the deep link to the Gaussian Splatting channel to work. If so, we should probably update the link in SuperSplat's Help menu to the generic server link.

**Comment by simonbethke** [comment]
Yea, I also think so.
