### ISSUE TITLE
ply property 

### ISSUE THREAD

**Issue by leejngmn** [playcanvas/supersplat#203]
Hello! supersplat is very useful and I am so grateful for providing it.

I have a ply that I need to view in supersplat. 
Can I open it in supersplat by adding arbitrary properties that I need?

What are the properties of the file that supersplat needs?
What is the float f_rest property?

- my ply 
(['ply\r\n',
  'format binary_little_endian 1.0\r\n',
  'comment Exported by Geomagic\r\n',
  'element vertex 133992\r\n',
  'property float x\r\n',
  'property float y\r\n',
  'property float z\r\n',
  'end_header\r\n'],

- Any ply I can see in supersplat
 ['ply\n',
  'format binary_little_endian 1.0\n',
  'element vertex 117074\n',
  'property float x\n',
  'property float y\n',
  'property float z\n',
  'property float nx\n',
  'property float ny\n',
  'property float nz\n',
  'property float f_dc_0\n',
  'property float f_dc_1\n',
  'property float f_dc_2\n',
  'property float f_rest_0\n',
  'property float f_rest_1\n',
  'property float f_rest_2\n',
  'property float f_rest_3\n',
  'property float f_rest_4\n',
  'property float f_rest_5\n',
  'property float f_rest_6\n',
  'property float f_rest_7\n',
  'property float f_rest_8\n',
  'property float f_rest_9\n',
  'property float f_rest_10\n',
  'property float f_rest_11\n',
  'property float f_rest_12\n',
  'property float f_rest_13\n',
  'property float f_rest_14\n',
  'property float f_rest_15\n',
  'property float f_rest_16\n',
  'property float f_rest_17\n',
  'property float f_rest_18\n',
  'property float f_rest_19\n',
  'property float f_rest_20\n',
  'property float f_rest_21\n',
  'property float f_rest_22\n',
  'property float f_rest_23\n',
  'property float f_rest_24\n',
  'property float f_rest_25\n',
  'property float f_rest_26\n',
  'property float f_rest_27\n',
  'property float f_rest_28\n',
  'property float f_rest_29\n',
  'property float f_rest_30\n',
  'property float f_rest_31\n',
  'property float f_rest_32\n',
  'property float f_rest_33\n',
  'property float f_rest_34\n',
  'property float f_rest_35\n',
  'property float f_rest_36\n',
  'property float f_rest_37\n',
  'property float f_rest_38\n',
  'property float f_rest_39\n',
  'property float f_rest_40\n',
  'property float f_rest_41\n',
  'property float f_rest_42\n',
  'property float f_rest_43\n',
  'property float f_rest_44\n',
  'property float opacity\n',
  'property float scale_0\n',
  'property float scale_1\n',
  'property float scale_2\n',
  'property float rot_0\n',
  'property float rot_1\n',
  'property float rot_2\n',
  'property float rot_3\n',
  'end_header\n'])

**Comment by slimbuck** [comment]
Hi @leejngmn ,

Supersplat expects all the data above except the f_rest_ data, which is the spherical harmonics and nx,ny,nz. If you add the rest as float properties Supersplat will load it.

You could also update supersplat loader to add the missing data.

I've done this myself actually and I can suggest you start with a very small scene while developing. It's extremely easy to create a scene with huge massive overlapping splats that will end up crashing the browser tab (because the gpu takes too long to render).

Thanks!

**Comment by slimbuck** [comment]
Nothing to do.
