### ISSUE TITLE
Why is the display effect lower than expected

### ISSUE THREAD

**Issue by DreamerYinYu** [playcanvas/supersplat#210]
Hello, I used supersplast and Unity to test the display effect of my ply file separately. Why is the display effect lower than expected in supersplast? Is there a problem with my ply file? Or am I using it improperly? thank you

supersplast：
![微信截图_20241010152359](https://github.com/user-attachments/assets/ae472059-e92f-4f76-89d4-2d1dc0310c8a)

unity：
![微信图片_20241010152709](https://github.com/user-attachments/assets/c856a750-9552-48ab-a093-a9151a1af4b7)

**Comment by slimbuck** [comment]
The baidu website doesn't allow me to download the file without installing an app (?!?). So if you can send to my email that'd be great thanks: slimbuck7@gmail.com.

**Comment by DreamerYinYu** [comment]
Okay, it has been sent to you. Thank you very much

**Comment by slimbuck** [comment]
Thanks I got the file and will take a look, hopefully in the next few days.

**Comment by DreamerYinYu** [comment]
> 谢谢我拿到了文件，希望在接下来的几天里能看一下。

Hello, have you tested it? thank you

**Comment by slimbuck** [comment]
Hi @DreamerYinYu ,

I looked at your scene in Supersplat and Postshot and I don't see a big difference to be honest.

The scene is quite noisy and I suspect the viewpoint must be perfectly aligned to cameras.json for it look good. If the camera is off at all off then the scene looks noisy.

Supersplat doesn't actually set the camera pose _exactly_ (camera FOV isn't set and the camera twist isn't set) and perhaps that is making the difference in this case.

Either way, I don't think you're doing anything wrong on your end. All I can suggest is to improve your model by taking more photos from different locations in the space.

Thanks!

**Comment by willeastcott** [comment]
Closing this issue. If you believe there is still a problem, please reopen it @DreamerYinYu.

**Comment by sadhasld** [comment]
Hello, how do you use to display splat in Unity? It looks like it works well
