### ISSUE TITLE
Value field manipulation with mouse doesn't work

### ISSUE THREAD

**Issue by simonbethke** [playcanvas/supersplat#212]
There is this kind of number-input that shows a left-right arrow when hovering to indicate that you can decrease the value by dragging it left and increase it by dragging it right. 
However, when modifying the position of a splat, you can drag left and it decreases, now drag right and it continues to decrease.
When creating a sphere for sphere-selection and you drag the radius field, the sphere size gets increased in both directions.

**Comment by slimbuck** [comment]
@simonbethke could you please retest this? I believe this happened with me once, but haven't been able reproduce since. (I believe this was fixed with a recent gizmo update).

**Comment by slimbuck** [comment]
Closing, but please reopen if you do find this still happens.
