### ISSUE TITLE
The speed of saving ply which is bigger than 2G is slow

### ISSUE THREAD

**Issue by Deaddawn** [playcanvas/supersplat#214]
Hi, there. I'm trying to save .ply bigger than 2G and it's extremely slow, (I have to use full ply without compressed or other format), any idea how to solve this?

**Comment by slimbuck** [comment]
Hi @Deaddawn ,

How long are we talking for the 2gb to save? Which browser and hardware/platform?

Thanks!

**Comment by Deaddawn** [comment]
> Hi @Deaddawn ,
> 
> How long are we talking for the 2gb to save? Which browser and hardware/platform?
> 
> Thanks!
Hi, here are the details:

**Situation:** try to merge three .ply (1.3G, 517M, 619M)
**Saving duration:** At least 1hrs 30m, never finished
**Browser:** Chrome
**Hardware:** CPU: Intel(R) Core(TM) Ultra 7 || RAM: 64G || GPU: nvidia etx 2000

I tried to run both live and local and fail. Thank you for taking a look at this problem

**Comment by slimbuck** [comment]
Ah ok, sounds like it's completely failing (shouldn't take more than a few minutes at most).

It might be an out of memory issue, not sure. Does the devtools log show any error?

**Comment by Deaddawn** [comment]
> Ah ok, sounds like it's completely failing (shouldn't take more than a few minutes at most).
> 
> It might be an out of memory issue, not sure. Does the devtools log show any error?

Not sure whether the log show any error, the node program is running in background, guess I will take a look and come back to you later.

**Comment by Deaddawn** [comment]
> Ah ok, sounds like it's completely failing (shouldn't take more than a few minutes at most).
> 
> It might be an out of memory issue, not sure. Does the devtools log show any error?

![image](https://github.com/user-attachments/assets/1bea97b1-18ac-40af-9bdb-40246983359e)

Well, I guess no error?

**Comment by Deaddawn** [comment]
> Try opening the developer tools window of the browser itself (cmd+option+i on my machine) and check the console log there.

Thank you for reminding me, and I'm getting this:
![image](https://github.com/user-attachments/assets/b21f5a4f-c1df-4a48-a5b9-fd1488a09007)

**Comment by slimbuck** [comment]
It looks like you're using supersplat v1.4.0. Is there any reason for this? The latest version is v1.5.2.

Either way Supersplat should display an error message in this case and not just continue to show busy icon.

**Comment by Deaddawn** [comment]
> It looks like you're using supersplat v1.4.0. Is there any reason for this? The latest version is v1.5.2.
> 
> Either way Supersplat should display an error message in this case and not just continue to show busy icon.

Same for v1.5.2

![image](https://github.com/user-attachments/assets/48685ec7-b4e8-41c3-8484-55b2ea040214)

**Comment by Deaddawn** [comment]
And the error tracebacks to the following code: 

![image](https://github.com/user-attachments/assets/d7a0aaec-0182-43bb-a896-2357c62d6e8c)

**Comment by slimbuck** [comment]
Oh this is actually very useful, thanks so much.

This is the saving code which allocates an entire copy of the output before processing begins.

I am about to look at this code which must now be updated to handle arbitrary splat transforms

I might try restructure the code to stream the data out, instead of allocating the entire output buffer like this.

**Comment by Deaddawn** [comment]
> Oh this is actually very useful, thanks so much.
> 
> This is the saving code which allocates an entire copy of the output before processing begins.
> 
> I am about to look at this code which must now be updated to handle arbitrary splat transforms.
> 
> I might try restructure the code to stream the data out, instead of allocating the entire output buffer like this.

Wonderful!

**Comment by Deaddawn** [comment]
Any luck on this one?

**Comment by slimbuck** [comment]
Closing, but please reopen if you find any issues.

**Comment by Deaddawn** [comment]
> Hey @Deaddawn,
> 
> Good timing!
> 
> We just released v1.7.1 which fixes a bug that was allocating tons of memory unnecessarily at save time. It also includes streaming output for PLY. See #222.
> 
> Thanks!

great !
