### ISSUE TITLE
Custom canvas background color

### ISSUE THREAD

**Issue by RobLinkA** [playcanvas/supersplat#215]
Some point clouds have low opacity, light colors or are close to the background, which often causes them to be ignored. I hope to add the background color customization of the entire canvas in the settings menu, so that it will be easier to clean up messy points.

**Comment by slimbuck** [comment]
Just so you know, you can already set the background color using a URL parameter like so:

https://playcanvas.com/supersplat/editor?bgClr=0.1,0.2,0.3
