### ISSUE TITLE
Add orthographic view

### ISSUE THREAD

**Issue by lesath3d** [playcanvas/supersplat#220]
Hello,

If you could build in these features it would be awesome!

-lasso tool
-orthographic view
-model based origin, not bounding box based
-full transparency mode for hide
-select by splat size in data panel
-rename the objects in scene manager

Thank you for your hard work guys, this is a very useful stuff!!
Have a nice day!

**Comment by slimbuck** [comment]
Hi @lesath3d ,

Thanks for submitting these requests! It really helps to know what users need.

Some comments:
- lasso tool: simple 2d version should be easy to add, just a different brush tool (perhaps @simonbethke would be interested in having a go!)
- orthographic view: do you mean a toggle between perspective/ortho views?
- model based origin: I'm curious why you want or need this? (not hard to add)
- full transparency: agree! easy to add!
- select by splat size: this is already possible in the data panel. Do you need something else? We already support:
    - splat volume
    - splat surface area
    - scale x, y z
- rename: once we support copy/paste the scene manager will store selection sets etc and allow rename

**Comment by lesath3d** [comment]
hi @slimbuck,

Thank you for your quick answer!

-lasso: great news! It will help a lot with cleaning!
-orthographic view: yes a switch would be great between perspective/ortho view. I tried the field of view function but I think a simple switch would be better.
-model based origin: since I can load multiple models, when I delete a part what needed(and I can't undo it, because it was long ago) I load the original model, cut off the area what I need and use it like a patch but I can't do it if I made any transform on the model and I did a modification on that. If the origin would be the same always I could use transform, which is incredible helpful function.
-splat size: I'm using a lot the data panel. I tested it backwards. I selected the biggest and try to find out which value will match and I didn't find that. Scale which is box based would be helpful to cut off the biggest splats.

**Comment by Hbm1g18** [comment]
Hi @slimbuck 
> * model based origin: I'm curious why you want or need this? (not hard to add)
I'm interested in this from a georeferenced model view.
I'm generating some gaussian splats that I would like to have placed geographically correct. I'm able to do this and bring them into supersplat, however due to their coordinate values being quite extreme (relative to 0,0,0) it can be difficult to then edit and clean them up. 

I think an option to either zoom to selection, set origin at a given point or automatically have the origin within the model would be a nice addition. 

Currently I can zoom roughly to the location of the splats, but due to the zooming speed I can't get close enough to make precise edits to the model

Thanks for all the work on this tool

**Comment by slimbuck** [comment]
Hi @Hbm1g18,

Thanks so for your input.

From your description it sounds like locating the splat after loading is your issue. Is that right?

If so then I'm not sure 'model based origin' will help much in your case.

Things you could try:
- You can zoom to selection with 'F' key (or 'Frame Selection' on the right toolbar). If you've selected individual splats, these will be framed.
- You can double click anywhere on the scene to set the camera's focus point. Then the camera will orbit around that point. Might help in your case, not sure.
- Double-clicking anywhere on the scene with a transform gizmo activated (translate/rotate/scale) will place the gizmo at that point.
- If the splat is far from the center after loading, try setting its position (in the TRANSFORM panel) to (0, 0, 0). The splat might now be in the wrong place for export though.

If none of these work for you, it would be great if you could make a little video or send me the PLY so I understand better. Perhaps we can find a solution.

Thanks!
