### ISSUE TITLE
Question about the change of output ply file format

### ISSUE THREAD

**Issue by oUp2Uo** [playcanvas/supersplat#225]
Hi, it seems that recently update add comments and transform property, and this make the output ply file could not be recongnized by many other GS programs (which just pass fixed lines and read the contents).

Is there a way not to output `comment Generated by superSplat 1.7.1` and `property float transform`?

![1](https://github.com/user-attachments/assets/36c83700-f282-4bc3-8dde-25039eeb5ff6)
![2](https://github.com/user-attachments/assets/5b9a4e6e-a33b-4b4b-a946-3ef3671c3099)

Thank you.

**Comment by slimbuck** [comment]
Oh gosh that's pretty terrible support from the other tools!!

We will this change today in that case and perhaps add an option to include the extra comment for users that want it.

**Comment by oUp2Uo** [comment]
Thanks for the reply.
Maybe add options for extra function is a good solution.

**Comment by willeastcott** [comment]
Fixed by https://github.com/playcanvas/supersplat/pull/226
