### ISSUE TITLE
Could not able to load 3DGS model

### ISSUE THREAD

**Issue by hardikdava** [playcanvas/supersplat#227]
Hello developers, I am trying to visualize trained 3DGS model. But I am facing this error. Thanks in advance. 

OS: ubuntu 22.04
Browser: Google Chrome
GPU: yes
Loading method: tried both drag & drop and using open button

![Screenshot from 2024-10-23 12-35-06](https://github.com/user-attachments/assets/7389ca87-70ad-4a87-8437-762409e6fa0a)

**Comment by hardikdava** [comment]
@slimbuck Done.

**Comment by slimbuck** [comment]
Thanks @hardikdava.

Is this a recent change? Have you done this before on this system?

**Comment by hardikdava** [comment]
@slimbuck Yes, this is very recent change. I tried firefox and seems working but not with chrome.

**Comment by slimbuck** [comment]
CSP should be fine on the scripts. Not sure what to suggest. Perhaps cloudfront had a blip? Could you try loading again after clearing cache?

**Comment by hardikdava** [comment]
@slimbuck Tried but not resolved.

**Comment by slimbuck** [comment]
Unless we can reproduce there is not much we can do here unfortunately.

Please re-open this issue if you know how we can repro.
