### ISSUE TITLE
PLY Header Invalid when importing to UE5.4 via XV3DGS

### ISSUE THREAD

**Issue by nathanssu** [playcanvas/supersplat#230]
Hi there!

I'm trying to load a Gaussian Splat .ply that was created in Postshot then cropped in Supersplat to UE5 via the XV3DGS plugin. The uncropped .ply loads fine, but after saving from supersplat (1.7.2) I get an invalid headers error. (see screenshot)

![Screenshot 2024-10-23 143953](https://github.com/user-attachments/assets/6cb8bd38-4314-4e0f-aa08-b5d22fe9425a)

In previous versions of supersplat (0.19.2) I was able to save from supersplat without this issue occuring. 

Many thanks for your help!
Nathan

**Comment by slimbuck** [comment]
Hi, are you able to post an example of the original and modified version?

**Comment by nathanssu** [comment]
here's a folder with 3 files - the original, one modified in 0.19.2 (works in UE5), and one modified in 1.7.2 (has the invalid headers issue). 

https://drive.google.com/drive/folders/1DhZwTLSPPT797ZHs-VwtRVnaa1pD5OJj?usp=sharing

**Comment by slimbuck** [comment]
Actually I found the issue. Fix will be deployed sooon.

**Comment by nathanssu** [comment]
perfect thank you so much! really appreciate it!

**Comment by slimbuck** [comment]
Fixed in #231 and deployed to prod.
