### ISSUE TITLE
Is there a way we could render an image with a certain view?

### ISSUE THREAD

**Issue by Deaddawn** [playcanvas/supersplat#238]

**Comment by slimbuck** [comment]
Hi @Deaddawn , 

Do you mean you want to download a PNG image of the current view or something else?

Downloading a png of the viewport would be easy to implement, though I guess we'd want to hide the grid/bounding box/selections etc.

Thanks

**Comment by Deaddawn** [comment]
> Hi @Deaddawn ,
> 
> Do you mean you want to download a PNG image of the current view or something else?
> 
> Downloading a png of the viewport would be easy to implement, though I guess we'd want to hide the grid/bounding box/selections etc.
> 
> Thanks

Yes, would that be possible to tell us how to do this?

**Comment by slimbuck** [comment]
I will add that today 👍🏻 (but without automatically hiding bits).

**Comment by Deaddawn** [comment]
> I will add that today 👍🏻 (but without automatically hiding bits).

Thanks a lot! Does "hiding bits" means I can't hide grid or selections? If so, it will be a little inconvenience :joy:

**Comment by slimbuck** [comment]
Yes you'll just have to hide the grid yourself before taking the screenshot for now, that's all.

Otherwise we must add options to the UI to 'include grid in screenshot' etc, which I'd rather not do right now.

**Comment by slimbuck** [comment]
Btw the png will have transparent background, is that ok?

**Comment by Deaddawn** [comment]
> Yes you'll just have to hide the grid yourself before taking the screenshot for now, that's all.
> 
> Otherwise we must add options to the UI to 'include grid in screenshot' etc, which I'd rather not do right now.

Understand, thanks.

**Comment by Deaddawn** [comment]
> Btw the png will have transparent background, is that ok?

white bg would be great if possible 😂

**Comment by Deaddawn** [comment]
God speed! Master Jedi

**Comment by Deaddawn** [comment]
Sry to ask, I didn't find the screen shot button in the live version, should I run this locally?

**Comment by slimbuck** [comment]
Yes code is merged, but is still to be published on playcanvas.com. That'll happen today or tomorrow most likely.

Use local version if you need it now.

**Comment by Deaddawn** [comment]
> Yes code is merged, but is still to be published on playcanvas.com. That'll happen today or tomorrow most likely.
> 
> Use local version if you need it now.

I understand that background can not be adjusted in the current verson, would that be possible that you can tell me the code where i can just change the background into white. Thanks in advance

**Comment by slimbuck** [comment]
We will add background color picker real soon.

Till then change this constant to 255:

https://github.com/playcanvas/supersplat/blob/main/src/editor.ts#L554

**Comment by slimbuck** [comment]
I did this one too @Deaddawn #243

**Comment by Deaddawn** [comment]
> I did this one too @Deaddawn #243

Got it, that helps a lot, thanks !
