### ISSUE TITLE
Select by splat size in data panel

### ISSUE THREAD

**Issue by lesath3d** [playcanvas/supersplat#242]
hello @willeastcott,
as you asked, I just opened a new request for selecting splats by size in data panel.

**Comment by alexey7783** [comment]
I strongly support this request! This would be a great addition to the toolset. I imagine it like a slider with lower and upper value, like the price selection at Amazon

**Comment by slimbuck** [comment]
So this is currently possible, but with a slightly different UX.

On the data panel, select either volume or surface area (two ways of measuring total size), then click and drag on the histogram to select the range you're interested in.

It is possible there is a more useful ways to calculate splat size, like max(scaleX, scaleY, scaleZ) or similar.

If you have a chance please try this approach and let me know how that works for you.

**Comment by slimbuck** [comment]
Ahh great.

Just to add:
- holding shift adds to current selection
- holding ctrl removes from current selection

**Comment by lesath3d** [comment]
@slimbuck hey, yeah it works! I tried them with the early versions of supersplat and that wasn't what I wanted, but now it looks good. thank you! (PS: can't wait for the lasso :D )
