### ISSUE TITLE
visualization of gaussian balls

### ISSUE THREAD

**Issue by zhouilu** [playcanvas/supersplat#247]
Hi, Do you support Gaussian balls visualization?

**Comment by slimbuck** [comment]
I don't think so @zhouilu , what is that?

**Comment by zhouilu** [comment]
Thanks for your reply.
Gaussian balls visualization like this
![image](https://github.com/user-attachments/assets/80144523-e54c-4dd7-a658-62169d371b6a)

**Comment by slimbuck** [comment]
We have "rings" mode which is perhaps similar? Try loading a splat and pressing "m" or use the button top middle of the screen to toggle mode.

**Comment by zhouilu** [comment]
thanks, it is very similar. And can the ring thickness be displayed?

**Comment by slimbuck** [comment]
Do you mean can the thickness be changed? Not currently. Is that something you'd want?

**Comment by zhouilu** [comment]
Displays the thickness of the Gaussian balls, that's i want to.

**Comment by slimbuck** [comment]
I'm not really sure what they're doing in the paper to shade the gaussians, but I updated rings mode to render something similar in https://github.com/slimbuck/supersplat/tree/balls-dev:

<img width="1482" alt="Screenshot 2024-10-30 at 08 50 55" src="https://github.com/user-attachments/assets/403c39b3-ff1a-4770-99f5-ce5ec089cb2c">

You can checkout that branch and try it if you like.

**Comment by zhouilu** [comment]
Thank you very much.

**Comment by FudongGe** [comment]
> I'm not really sure what they're doing in the paper to shade the gaussians, but I updated rings mode to render something similar in https://github.com/slimbuck/supersplat/tree/balls-dev:
> 
> <img alt="Screenshot 2024-10-30 at 08 50 55" width="1482" src="https://private-user-images.githubusercontent.com/11276292/381464087-403c39b3-ff1a-4770-99f5-ce5ec089cb2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjE5MTksIm5iZiI6MTczMjc2MTYxOSwicGF0aCI6Ii8xMTI3NjI5Mi8zODE0NjQwODctNDAzYzM5YjMtZmYxYS00NzcwLTk5ZjUtY2U1ZWMwODljYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAyNDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzExM2QzOGEzNWUzNzI4NWQ3N2Q1NWUxZTM3N2U3NDNhZTkxNzNmOTFkNDdmNTA1N2JhZDY3ZjE0YTNmMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6OftQ2_vw-9ZXES5soTv4OfCZA5Y-fQ7vFVfzir5MTE">
> You can checkout that branch and try it if you like.

Hi, is the Gaussian sphere shading function available in the web version?

**Comment by slimbuck** [comment]
Hi @FudongGe,

I didn't add it to the main application. Would you also be interested in this rendering option?

**Comment by FudongGe** [comment]
> Hi @FudongGe,
> 
> I didn't add it to the main application. Would you also be interested in this rendering option?

Thank you for your quick reply!

Yes, I'm very interested in it. Moreover, it has been utilized in many papers, so I believe it could be useful to many people.
