### ISSUE TITLE
AMD CPU Integrated graphics support.

### ISSUE THREAD

**Issue by zach-pei** [playcanvas/supersplat#256]
AMD CPU Integrated graphics support. it seems like that this render engine dose not support AMD CPU Integrated graphics(AMD r5 5600u)

**Comment by zach-pei** [comment]
AMD CPU Integrated graphics support. it seems like that this render engine dose not support AMD CPU Integrated graphics(AMD r5 5600u)

**Comment by zach-pei** [comment]
Fixed,it is the Problem of Edge explorer

**Comment by slimbuck** [comment]
Great, closing.
