### ISSUE TITLE
Question about brush select and picker select

### ISSUE THREAD

**Issue by LaFeuilleMorte** [playcanvas/supersplat#259]
Hi, I've tried the selection functionality in the editor. But the brush select was not what I expected. 

<img width="530" alt="image" src="https://github.com/user-attachments/assets/eeca0365-db87-4959-a779-c8db3bb9745c">

There seemed to be only small amount of splats were selected. Not splats within the coverage of the rectangle. What I wanted to do is to select every splat inside the rect and delete its outer splats.

**Comment by slimbuck** [comment]
Hi @LaFeuilleMorte ,

SuperSplat has two modes, centers and rings.

It looks like you're in rings mode, which selects the top layer of splats. Centers mode selects all splats who's center falls within the rect.

Try toggling to centers mode using 'm' or the button at the middle top of the screen and trying again.

Let me know if that helps!
