### ISSUE TITLE
cannot visualize my gaussian_ply correctly 

### ISSUE THREAD

**Issue by yanyan-li** [playcanvas/supersplat#264]
Hello! supersplat is very useful and I am so grateful for providing it.

My model can render the following images, but the model can be visualized. 
Has anyone encountered the same problem and have any suggestions?

![image](https://github.com/user-attachments/assets/124e779d-53a5-498a-9f3c-cc2d7c57b59e)

![image](https://github.com/user-attachments/assets/88ebf7af-4df2-4dc1-bb59-e11d8416fc7d)

![image](https://github.com/user-attachments/assets/f3d86ca4-8321-46ae-9d2a-286a765f1945)

**Comment by slimbuck** [comment]
Hi @yanyan-li ,

Not sure. Can you send me the ply to take a look?

Thanks

**Comment by yanyan-li** [comment]
> Hi @yanyan-li ,
> 
> Not sure. Can you send me the ply to take a look?
> 
> Thanks

Hi @slimbuck , thanks for your reply. The ply file is attached. 
[0_gs_smilesplat.zip](https://github.com/user-attachments/files/17647141/0_gs_smilesplat.zip)

Thank you very much

**Comment by slimbuck** [comment]
Thanks @yanyan-li.

Where did you get this model?

It looks like scale_0, scale_1, scale_2 are just way too big, but also it looks like it could be 2dgs scene?

Anyway if I scale the splat sizes down you can see something, but still doesn't look correct:

<img width="1259" alt="Screenshot 2024-11-06 at 12 50 20" src="https://github.com/user-attachments/assets/91db075c-fdda-49ae-b7f8-8bd2d1c585a8">

**Comment by slimbuck** [comment]
Are you storing the log of the scale?

**Comment by slimbuck** [comment]
(GS ply stores log scale, not scale directly).

**Comment by yanyan-li** [comment]
> (GS ply stores log scale, not scale directly).

Hi @slimbuck  
Thank you so much for the great help.  We will acknowledge your tool when we open source our code. 

Best,
Yanyan

![img_v3_02gc_393d0968-f04f-4781-9e40-34dfe755855g](https://github.com/user-attachments/assets/d81b5d1d-0457-4112-adc8-32f76ffbfa0d)

**Comment by slimbuck** [comment]
Wonderful! Happy to help!
