### ISSUE TITLE
how to get gauss attribute in shader?

### ISSUE THREAD

**Issue by zhouilu** [playcanvas/supersplat#280]
Hi, i want to add some test code, but got some errors.
```
 mat3 rot = quatToMat(getRotation());
 vec3 n_world = rot[2];
 vec4 n_view =  model_view * vec4(n_world, 1.0);
  float x = dot(splat_cam.xyz, n_view.xyz);
  if (dot(splat_cam.xyz, n_view.xyz) < 0.0) {
       gl_Position = discardVec;
       return;
   }

ERROR: 0:190: 'getRotation' : no matching overloaded function found
ERROR: 0:190: 'quatToMat' : no matching overloaded function found
```
can you give some advices? Thanks

**Comment by slimbuck** [comment]
Hi @zhouilu , sorry but I'll need more context of where you're doing this. Can you share your branch or file or...?

**Comment by zhouilu** [comment]
Hi, like render with cull back.. I want to add this oparation into splat-shader.ts, so i need gauss rotation to compute normal.
```
    // handle transforms
    mat4 model_view = matrix_view * model;
    vec4 splat_cam = model_view * vec4(center, 1.0);

  // cull back here ???

    // cull behind camera
    if (splat_cam.z > 0.0) {
        gl_Position = discardVec;
        return;
    }
```
Is the code location correct?

**Comment by slimbuck** [comment]
Hi @zhouilu,

The gaussians don't have a backface though? They're blobs in space and we construct a camera-facing quad over the blob in the vertex shader at render time.

Also, just so you know, the shader doesn't have the gaussian's rotation and scale. We calculate a covariance matrix from rotation and scale on CPU and upload this for render (as a performance optimisation).

[Here](https://github.com/playcanvas/supersplat/blob/main/src/shaders/splat-shader.ts#L92) you can see we read the covariance, not rotation/scale.

Perhaps if you can explain what you're trying to cull I can help more!

**Comment by zhouilu** [comment]
> Hi @zhouilu,
> 
> The gaussians don't have a backface though? They're blobs in space and we construct a camera-facing quad over the blob in the vertex shader at render time.
> 
> Also, just so you know, the shader doesn't have the gaussian's rotation and scale. We calculate a covariance matrix from rotation and scale on CPU and upload this for render (as a performance optimisation).
> 
> [Here](https://github.com/playcanvas/supersplat/blob/main/src/shaders/splat-shader.ts#L92) you can see we read the covariance, not rotation/scale.
> 
> Perhaps if you can explain what you're trying to cull I can help more!

yes, i know use covariance matrix in shader. Backface though is a trick, it also as a performance optimisation. If gauss normal are calculated，we can cull backface when pre-rendering. 
So, how to get gauss rotation and calc normal? Or have any better method? Thanks

**Comment by slimbuck** [comment]
Hi @zhouilu ,

This sounds very interesting, I'd love to know more!

Right now though, I don't understand enough to suggest anything useful.

Thanks!

**Comment by zhouilu** [comment]
Thanks for replying again. I solved by passing rotate texture info shader. So i close this issue.

**Comment by slimbuck** [comment]
Hi @zhouilu ,

I have been considering changing our render pipeline to use rotations and scales instead of covariance matrix precisely so we have more flexibility in the shader. Is that somewhat that would have helped in your situation?

Thanks!

**Comment by zhouilu** [comment]
> Hi @zhouilu ,
> 
> I have been considering changing our render pipeline to use rotations and scales instead of covariance matrix precisely so we have more flexibility in the shader. Is that somewhat that would have helped in your situation?
> 
> Thanks!

yes, I think it will be very flexible.
