### ISSUE TITLE
On open of the exported html, the initial camera position is far away from the point cloud 

### ISSUE THREAD

**Issue by pavanadv** [playcanvas/supersplat#282]
On opening of the exported html, the initial camera position is far from the point cloud  and have to zoom in a lot, inorder to get to the point cloud. Need a way such that the exported html also captures the camera selection from the Poses, eg: camera_0 or camera_1 etc.. whichever pose is chosen, should also get captured in the exported html and it will open as the pose in the exported html

**Comment by slimbuck** [comment]
Yes we'll do this ASAP!

**Comment by slimbuck** [comment]
Done in #314, to be released soon.
