### ISSUE TITLE
Arrow-keys camera-flight sudden turn-around

### ISSUE THREAD

**Issue by simonbethke** [playcanvas/supersplat#286]
When flying forward with the up-arrow-key through the origin or focal-point or whatever, the camera suddenly turns around and you continue flying backward.

In this video I am holding the UP-Arrow all the time (additionally CTRL which doesn't change the general-behavior... it's just slower)

https://github.com/user-attachments/assets/f286e2a8-1ee7-4d93-82e2-5f5b89ad2834

**Comment by slimbuck** [comment]
Hilarious! We left a surprise singularity at the center of the world!

**Comment by simonbethke** [comment]
Lets hope this singularity can record all data of all time :)
