### ISSUE TITLE
About the coordinate system

### ISSUE THREAD

**Issue by zhouilu** [playcanvas/supersplat#289]
I am confused whether x and y in the coordinate system should be multiplied by -1 so that the openGL coordinate system can be used? Where is this transformation implemented? Can you tell me? Thanks!

![image](https://github.com/user-attachments/assets/290b63cb-6b29-47dd-bda9-a0bc94965800)

This is the coordinate system of the upper right corner of superSplat, but x, y and the real position are reversed.

**Comment by zhouilu** [comment]
At the same time, I saw that negative signs were added to x and y when loading camera json.
```
const loadCameraPoses = async (url: string, filename: string, events: Events) => {
    const response = await fetch(url);
    const json = await response.json();
    if (json.length > 0) {
        // calculate the average position of the camera poses
        const ave = new Vec3(0, 0, 0);
        json.forEach((pose: any) => {
            vec.set(pose.position[0], pose.position[1], pose.position[2]);
            ave.add(vec);
        });
        ave.mulScalar(1 / json.length);

        json.forEach((pose: any, i: number) => {
            if (pose.hasOwnProperty('position') && pose.hasOwnProperty('rotation')) {
                const p = new Vec3(pose.position);
                const z = new Vec3(pose.rotation[0][2], pose.rotation[1][2], pose.rotation[2][2]);

                const dot = vec.sub2(ave, p).dot(z);
                vec.copy(z).mulScalar(dot).add(p);

                events.fire('camera.addPose', {
                    name: pose.img_name ?? `${filename}_${i}`,
                    position: new Vec3(-p.x, -p.y, p.z),
                    target: new Vec3(-vec.x, -vec.y, vec.z)
                });
            }
        });
    }
};
```

**Comment by slimbuck** [comment]
Hi @zhouilu ,

Yes correct. We rotate the model 180 degrees around the Z axis at load time. On the transform panel you will see this after loading a PLY.

Thanks!

**Comment by zhouilu** [comment]
> Hi @zhouilu ,
> 
> Yes correct. We rotate the model 180 degrees around the Z axis at load time. On the transform panel you will see this after loading a PLY.
> 
> Thanks!

Thanks~ 
Can you point me to the code? I can't find it.

**Comment by slimbuck** [comment]
The rotation is done in the PlayCanvas engine [here](https://github.com/playcanvas/engine/blob/main/src/framework/parsers/gsplat-resource.js#L77).

**Comment by zhouilu** [comment]
> The rotation is done in the PlayCanvas engine [here](https://github.com/playcanvas/engine/blob/main/src/framework/parsers/gsplat-resource.js#L77).旋转是[在](https://github.com/playcanvas/engine/blob/main/src/framework/parsers/gsplat-resource.js#L77)PlayCanvas 引擎中完成的。

Thanks~
