### ISSUE TITLE
Blur results when using exported app html

### ISSUE THREAD

**Issue by LaFeuilleMorte** [playcanvas/supersplat#290]
Hi, I've noticed an obvious blurriness  when using the exported app html to render my ply. Here're the comparation:

Using Editor:
<img width="605" alt="image" src="https://github.com/user-attachments/assets/33dcc1c0-a82a-402e-8dd2-010d657fe8d0">

Using exported HTML:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/ec81c339-a2b9-4715-a428-c374b7521a68">

As I take a deeper look into the code. The compressed ply will drop the SH values to save more bytes.  And this is the same with the exported app html.  Both the rendering results above were using compressed ply format. So I don't know why there's a big gap between these two formats. Is the app.html rendering pipeline different from that of the editor? Looking forward to your reply.

**Comment by slimbuck** [comment]
If these are both compressed models, then the likely culprit is devicePixelRatio. Perhaps @willeastcott can confirm?

**Comment by LaFeuilleMorte** [comment]
> devicePixelRatio

I viewed and log the devicePixelRatio variable in the console and found that in the editor: the value=1.8, while in the app.html, the value=2.0. Could that be the root cause?

**Comment by slimbuck** [comment]
I guess the two windows were on two different screens? This difference is close enough that it shouldn't make a difference.

However PlayCanvas can be configured to use devicePixelRatio or not. If not then then rendered image will be lower res (so more blurry).

It's possible the editor project is configured to use devicePixelRatio and viewer.html not.

**Comment by LaFeuilleMorte** [comment]
> I guess the two windows were on two different screens? This difference is close enough that it shouldn't make a difference.
> 
> However PlayCanvas can be configured to use devicePixelRatio or not. If not then then rendered image will be lower res (so more blurry).
> 
> It's possible the editor project is configured to use devicePixelRatio and viewer.html not.

No, they are displayed on same browser and same screen. Mine is Mac M3. BTW, how to enable devicePixelRatio in viewer.html

**Comment by slimbuck** [comment]
Not sure, but @willeastcott can help (assuming the issue is DPR).

**Comment by willeastcott** [comment]
Try changing <pc-app> to <pc-app high-resolution> in the exported html. Does that help?

**Comment by LaFeuilleMorte** [comment]
> Try changing <pc-app> to <pc-app high-resolution> in the exported html. Does that help?

Seemed not changing. Maybe I can send it to you to debug.

[cropped_mcmc_nov15.debug-viewer.html.zip](https://github.com/user-attachments/files/17772101/cropped_mcmc_nov15.debug-viewer.html.zip)

**Comment by willeastcott** [comment]
Yeah, it'd be useful to have the PLY.

**Comment by LaFeuilleMorte** [comment]
[cropped_mcmc_nov15.debug.compressed.ply.zip](https://github.com/user-attachments/files/17773896/cropped_mcmc_nov15.debug.compressed.ply.zip)
OK，

**Comment by willeastcott** [comment]
Ah, I see what's happening:

1. SuperSplat is rendering at the device's physical resolution: https://github.com/playcanvas/supersplat/blob/c91b223f947b372ae6af6d9d20db4eca6e09e315/src/scene.ts#L87
2. The HTML viewer is rendering at the device's CSS resolution. And the `high-resolution` attribute is broken in version 0.1.3 of the PlayCanvas Web Components. I've just submitted a fix here: https://github.com/playcanvas/web-components/pull/52

I'll now submit a PR that updates SuperSplat to the latest version of the Web Components.

@slimbuck, are you happy for the viewer to render at physical resolution? Any concerns about performance?

**Comment by slimbuck** [comment]
Performance might suffer so we'll ultimately make it an export option. For now I think it's probably fine though.

**Comment by LaFeuilleMorte** [comment]
Thanks for your quick response and fix. Now I can render at higher resolution in some high dpi devices. Sorry but one more question about the performance. The fps seemed to drop a lot compared to that rendered in supersplat editor when using high-resolution rendering in both environment. Does the supersplat editor use some acceleration techniques?

**Comment by willeastcott** [comment]
@LaFeuilleMorte Actually, I didn't deploy a fix yet! But it's coming in the next 24-48 hours! We're working hard to get this done. I suspect the reason for the difference in performance is that the HTML viewer has antialiasing enabled but SuperSplat has it disabled. I will include this in my fix.

**Comment by willeastcott** [comment]
@LaFeuilleMorte SuperSplat 1.9.1 was published today. This should make the exported HTML Viewer render with the same settings as SuperSplat (antialias is disabled but high-resolution is enabled). If you open the viewer HTML file and look for the `pc-app` element, you can edit these settings as you like them now. Let me know if you experience any more problems! 😄
