### ISSUE TITLE
Pinch to Zoom on Mac

### ISSUE THREAD

**Issue by s2dimensional** [playcanvas/supersplat#293]
Hi,
Just checking to see if anyone else is having the issue on SuperSplat 1.9.0 on Safari with pinch to zoom not working?
It functioned in previously. Would be great to fix.

Regards,
s2

**Comment by slimbuck** [comment]
Oh this is quite serious @s2dimensional, thanks so much for reporting. I will try push a fix for our tomorrow.

**Comment by slimbuck** [comment]
Hi @s2dimensional ,

I took a quick look and touch screen controls seemed to work fine on iphone.

Perhaps you're referring to touchpad pinch-to-zoom on mac? The v1.9.0 update did change the touchpad so all camera controls are possible. So now:
- two-finger swipe to camera orbit
- +shift to move camera left/right/up/down
- +ctrl to zoom

Pinch to zoom still works, but is much less sensitive. This is partly down to the strange browser events we're given.

Please let me know if this is what you're referring to and whether the slightly updated controls work for you.

**Comment by s2dimensional** [comment]
Hi @slimbuck 

Yes that was what I was referring to, the touch pad pinch to zoom on a Mac, specifically Safari.  Pinch to zoom on Safari is non-responsive and somewhat responsive on Chrome, but that is OK as +ctrl works just fine!

Sorry for any confusion. Keep up the excellent work!
s2
