### ISSUE TITLE
Spike artifacts appearing in certain viewing angles

### ISSUE THREAD

**Issue by RobLinkA** [playcanvas/supersplat#300]
![main object surface](https://github.com/user-attachments/assets/ffac2c46-d01d-40e5-a1bd-76be133ff583)
![main object surface](https://github.com/user-attachments/assets/a82a1535-5773-41a9-9d09-ac683d3fb1cd)
![oblique angle](https://github.com/user-attachments/assets/19f0f36c-de82-4dfe-b2e8-1fd378a3f75f)

When importing my 3D Gaussian Splatting model into Supersplat editor, I'm observing numerous spike-like artifacts in the point cloud. These artifacts have the following characteristics:

- They appear as needle-like protrusions from the main object
- The artifacts are particularly noticeable when viewing parallel to the main object surface
- When rotating to an oblique angle, the artifacts become less visible
- After deleting these spike artifacts, they tend to reappear

Questions

1. Is this a known issue with 3DGS models in Supersplat?
2. Are there any recommended settings or approaches to minimize these artifacts?
3. Could this be related to the optimization process during the initial 3DGS training?

**Comment by RobLinkA** [comment]
Here's the [splat file](https://drive.google.com/file/d/1d5HgcGhiH3eZVCJzB7--CJJoQ3MR67S5/view?usp=sharing)

**Comment by slimbuck** [comment]
Hi @RobLinkA,

It looks like this scene just contains very long and thin gaussian splats. I can select and delete them, but as you say, they appear and disappear depending on the view angle making it difficult to remove them all.

I also tried isolating them on the SPLAT DATA panel, by volume or surface area but didn't manage.

How did you train this scene? My first guess is the trainer is generating bad data. I will look at the raw file next though, perhaps it includes NaNs or similar.

> After deleting these spike artifacts, they tend to reappear

This shouldn't happen though...

**Comment by RobLinkA** [comment]
After further investigation, I found the spike artifacts are not from the original training, but appear after scaling the model:

1. Original models (both standard 3DGS and Postshot):
- Are normal without any spike artifacts
- Display correct visualization from all angles

2. After scaling operation:
- Standard 3DGS model shows spike artifacts
- Artifacts are especially visible when viewing parallel to the main object
- Different viewing angles affect the visibility of artifacts

This suggests the problem might be related to how Gaussian parameters (scale, shape, orientation) are handled during the scaling operation (for this case it's not done in Supersplat). The spikes could be a result of improper scaling of these parameters, causing some Gaussians to be abnormally stretched. So is there a recommended way to scale 3DGS models while preserving Gaussian properties? Thank you!

**Comment by slimbuck** [comment]
Hi @RobLinkA,

Have you tried scaling in SuperSplat instead? I haven't heard any users having issues with this.

**Comment by LaFeuilleMorte** [comment]
> After further investigation, I found the spike artifacts are not from the original training, but appear after scaling the model:
> 
> 1. Original models (both standard 3DGS and Postshot):
> 
> * Are normal without any spike artifacts
> * Display correct visualization from all angles
> 
> 2. After scaling operation:
> 
> * Standard 3DGS model shows spike artifacts
> * Artifacts are especially visible when viewing parallel to the main object
> * Different viewing angles affect the visibility of artifacts
> 
> This suggests the problem might be related to how Gaussian parameters (scale, shape, orientation) are handled during the scaling operation (for this case it's not done in Supersplat). The spikes could be a result of improper scaling of these parameters, causing some Gaussians to be abnormally stretched. So is there a recommended way to scale 3DGS models while preserving Gaussian properties? Thank you!

The scale are calculated with log functions: if you want to scale a gaussian,  use scale += scaling_ratio instead of scale *= scaling_ratio.
