### ISSUE TITLE
Loading assets on my server

### ISSUE THREAD

**Issue by LaFeuilleMorte** [playcanvas/supersplat#301]
Hi, I've made some changes in supersplat code:
change the asset path to a folder with my ply model on the server side. So when I run "nom run develop", it won't load from file picker, but load from the server end. 

I finally got this to work. But something was unnormal to me, the loading took about 3 minutes. But when loading from file picker, the loading only took seconds. Can you point out what am I doing wrong?

My change was here:
![image](https://github.com/user-attachments/assets/8a8df99c-efcb-47b5-955f-c628de6d0091)
in the file src/file-handler.ts from line 164 to 182

**Comment by slimbuck** [comment]
Hi @LaFeuilleMorte ,

If you open the developer tools, on the network tab, do you see the download itself take 3 minutes?

Thanks

**Comment by LaFeuilleMorte** [comment]
> Hi @LaFeuilleMorte ,
> 
> If you open the developer tools, on the network tab, do you see the download itself take 3 minutes?
> 
> Thanks

Yeah, I see. It's downloading models from the server.
