### ISSUE TITLE
camera.json format

### ISSUE THREAD

**Issue by DavidCao1993** [playcanvas/supersplat#304]
Thank you for your great jobs. I want to know the format of your camera.json so that i can create my own json file to import pose. and how to get the cameras.json? By the way, could you please add the function to export the pose
![image](https://github.com/user-attachments/assets/3189c815-a47f-45f6-ac42-e25667838e01)
 which I recorded by myself to the json file. thanks a lot.

**Comment by slimbuck** [comment]
Hi @DavidCao1993 ,  

The json format we currently support are the `cameras.json` generated by the original Inria trainer.

For example, the bicycle scene comes with this file:
[cameras.json](https://github.com/user-attachments/files/17958791/cameras.json)

You can drag and drop that onto SuperSplat and see the resulting poses in the panel.

We will soon add support for nerfstudio's cameras format (see https://github.com/playcanvas/supersplat/issues/297) and we will also support exporting the cameras from the CAMERA POSES panel (probably also in nerfstudio format).

Does this all sound reasonable? Would you like any other particular format supported?

Thanks!

**Comment by DavidCao1993** [comment]
thank you very much. Looking forward to your new features！！！

**Comment by kaikai23** [comment]
Hi, is this feature already supported in the https://playcanvas.com/supersplat/editor? When I drop my cameras.json file into it, there is an error:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/c2427f91-6bcd-4ab3-81da-57aedab90b67" />

**Comment by slimbuck** [comment]
Hi @kaikai23 , can you provide the cameras.json so I can investigate? Thanks

**Comment by kaikai23** [comment]
Hi,  I just used the cameras.json you provided above. 
I am using Microsoft Edge Version 112.0.1722.58 (Official build) (arm64), and SUPERSPLAT v1.13.1

**Comment by slimbuck** [comment]
Oh! I can repro, busy investigating. Thanks for report this!

**Comment by kaikai23** [comment]
Thanks for the quick reaction! However, after this fix is merged, I still got the same error.
Maybe the live editor hasn't been synchronized with the latest code? Could you confirm if you can drop cameras.json on the live editor now? Thanks!

**Comment by slimbuck** [comment]
Oh sorry no it's not live yet, but we'll probably do a release later today.

The fix will likely go out in v1.13.2 or v1.14.0 (depending on the other features we release today).

**Comment by slimbuck** [comment]
That's now live @kaikai23

**Comment by slimbuck** [comment]
Hi @kaikai23,

I hadn't actually tested this for a while and actually it wasn't working.

I've submitted a PR to fix this though https://github.com/playcanvas/supersplat/pull/445 which will be deployed soon.

Thanks for reporting the issue!
