### ISSUE TITLE
[Feature request] Filter selected splats/select by criteria

### ISSUE THREAD

**Issue by jonathantelfer** [playcanvas/supersplat#317]
I often need to make some tricky edits to remove specific splats that would be easier if it were possible to either select splats that match certain criteria, or filter splats out of the current selection if they match criteria. For example in this area I need to select and remove the large, white splats but not any smaller, detailed ones that they might be hiding:

![image](https://github.com/user-attachments/assets/4a1d4081-116d-4a04-93b9-0c5c5c5c0853)

In this area I need to remove small, white splats but keep any non-white splats of a similar size:

![image](https://github.com/user-attachments/assets/a07f1a25-8632-4c49-bc9d-e3e5abcc8d09)

And here I need to select only the blue splats:

![image](https://github.com/user-attachments/assets/64a20bc0-16bd-4e93-b806-167ca86e919d)

Being able to select or filter out of the selection by a combination of size, colour and transparency would be extremely useful and time-saving.

**Comment by slimbuck** [comment]
Hi @jonathantelfer,

Have you tried using the SPLAT DATA panel to do some of this?

If you haven't already, try opening the panel (located at the bottom of the screen) and select one of the criteria you're interested in from the dropdown panel.

You can then select splats directly on the histogram by clicking and dragging to update the selection:
- add with shift
- remove with ctrl
- or replace selection with neither

Unfortunately the plots are still a bit rudimentary. For example, the hue plot doesn't actually display the hue color. You only see values plotted between 0 and 360. However you can select a gaussian in the scene to see what its hue is on the histogram too, so you might find it helps nonetheless.

Also to mention that you select gaussians you're not interested in and lock them (from the selection menu).

This shows the SPLAT DATA panel in action:

https://github.com/user-attachments/assets/ad9ce194-5f6e-4cb8-b5fb-f8dbc18339d4

Hope that helps!

**Comment by jonathantelfer** [comment]
No way! I completely missed that you could select from that panel. That's saved me a ton of fiddly work, thanks so much for the quick response. Amazing. I really should RTFM sometimes 👍

**Comment by slimbuck** [comment]
Oh great I'm glad that works for you. We need better docs tbh, it's not at all obvious!

**Comment by jonathantelfer** [comment]
Have played around a bit and it works great. I just need to get out of RGB headspace and get comfortable selecting in HSV. The option to see the graph as log values is incredibly useful.
