### ISSUE TITLE
Unable to load the SuperSplat model viewer

### ISSUE THREAD

**Issue by sravaniPenumutchu** [playcanvas/supersplat#321]
Hi there, I'm new to playcanvas. I trying to pull in the SuperSpalt code and run it locally. 
I pulled in the code and ran "npm i" and "npm run develop" as instructed. I get this error where the "app" is undefined or parameter is not right type.

Could you please help with resolving this error?
![Untitled](https://github.com/user-attachments/assets/6701f52c-f1a5-4dd3-8d7b-22e1565e50a4)

**Comment by slimbuck** [comment]
Hi @sravaniPenumutchu , 

I'm not sure. I just pulled main from github and installed and ran fine.

What version of node are you on? We tend to use v18.20.4.

Thanks

**Comment by sravaniPenumutchu** [comment]
The node version I use is v20.14.0. Do you suggest downgrading the version might fix the issue?

**Comment by slimbuck** [comment]
Probably worth a try. Do you see any error messages on the console of the terminal you're serving from?

Also make sure you enable "Update on reload" and "Bypass for network" in Chrome devtools application->service workers tab:
<img width="1201" alt="Screenshot 2024-12-09 at 17 37 02" src="https://github.com/user-attachments/assets/68d78403-0434-4c7a-bde1-47983934468f">

Then perhaps try reload.

**Comment by sravaniPenumutchu** [comment]
Having the enabled "Update on reload" and "Bypass for network" in Chrome devtools application, seems work. The Canvas loaded without any errors. 
![Uploading Untitled.jpg…]()

**Comment by slimbuck** [comment]
Oh excellent. We use service workers to support PWA and offline access, but they are pain in the butt without those flags.

I think we should add those steps to the docs.

Thanks for confirming!

**Comment by sravaniPenumutchu** [comment]
I totally understand. Thank you
