### ISSUE TITLE
Export Issue

### ISSUE THREAD

**Issue by aelhakie** [playcanvas/supersplat#327]
Hello, first off, love your project! I have been using it extensively over the past 2 weeks to clean splats. Recently, I have had an issue with the export function. I usually import my splat as a ply file, clean it, then export it back. But today, whenever I remove too many gaussians, I cannot export the file, to any format. However if I remove just a few, it works just like it used to. Any help would be much appreciated.

**Comment by slimbuck** [comment]
Thanks for reporting this issue.

The fix has just deployed in v1.11.2 - please confirm it works for you!

**Comment by aelhakie** [comment]
Thanks for the quick reply!  I just tried it but unfortunately it still isn't working.

**Comment by slimbuck** [comment]
Please can you confirm you're running version v1.11.2? If not, then please refresh the tab.

**Comment by slimbuck** [comment]
(version is displayed bottom right)

**Comment by aelhakie** [comment]
You were right, I needed to refresh my browser. Thank you!
