### ISSUE TITLE
[Feature request] Support saving splat colors in URL parameters

### ISSUE THREAD

**Issue by RobLinkA** [playcanvas/supersplat#329]
I noticed that background color can be set via URL parameter (e.g., `bgClr=0.0,0.0,0.0`). It would be very useful to have similar URL parameters for:
- Selected splat color
- Unselected splat color

This would allow users to:
1. Save their preferred color configurations in browser bookmarks
2. Share specific visualization configurations via URLs
3. Maintain consistent settings across sessions without manual reconfiguration

Is this feature already supported? If so, could you please document the parameter names? If not, would you consider adding this functionality?

Current known URL parameter:
- Background color: `bgClr=r,g,b`

Related use case: When working with multiple models, I often need specific color configurations for better visualization. Being able to save these settings in bookmarks would significantly improve workflow efficiency.

**Comment by slimbuck** [comment]
Hi @RobLinkA ,

I can add this quite easily, but of course this solution is a band-aid.

We have plans afoot to implement a document format which will store all settings for a session, including these.

See #324 for details and feel free to comment there.

BTW any setting that appears in the [scene config object](https://github.com/playcanvas/supersplat/blob/main/src/scene-config.ts#L6) can be set via URL parameter. For example, to disable the debug overlay you use `&camera.debug=false`.

**Comment by slimbuck** [comment]
Checking the current scene config object I see (quite embarrassingly) that there are some legacy settings we must remove! `hideLeftShoe`?!? :D

**Comment by RobLinkA** [comment]
That's so nice! Thank you!
