### ISSUE TITLE
Unable to play rendering on iphone13 google chrome in exported html with 3rd SH cofficients in version v1.11.2

### ISSUE THREAD

**Issue by LaFeuilleMorte** [playcanvas/supersplat#337]
Hi, I've tried your newest compressing scheme, which was awesome. I can render the exported html on my desktop very well. But had trouble when rendering on my iphone 13 with google chrome. The webpage was stuck here:

![wecom-temp-43682-9f6f475395a9532bb7a5fa3599573424](https://github.com/user-attachments/assets/06f39faf-8120-484c-a85e-5661fd0cbb27)

I was using your latest v1.11.2 editor.

**Comment by slimbuck** [comment]
Hi @LaFeuilleMorte,

How big is your html file? Safari places limits on maximum size it will allow. If you can send us the file we can check this is the case.

If that is the issue we will release an update today which gives you the option of downloading a .zip file with external compressed.ply file. You must serve these files for it to work, but it doesn't have the same memory issue.

Thanks!

**Comment by slimbuck** [comment]
(And just to clarify, you said chrome on iOS, but chrome is just a skin over Safari on all iOS devices).

**Comment by LaFeuilleMorte** [comment]
> Hi @LaFeuilleMorte,
> 
> How big is your html file? Safari places limits on maximum size it will allow. If you can send us the file we can check this is the case.
> 
> If that is the issue we will release an update today which gives you the option of downloading a .zip file with external compressed.ply file. You must serve these files for it to work, but it doesn't have the same memory issue.
> 
> Thanks!

It's about 250 MB. That makes sense. In the previous versions. I exported html with no SH data. So the size would be only 65MB. But now it has SH data so it's much bigger and could possible cause this issue. I'll try smaller html with the same order of SH data to see if your conclusion is right.

**Comment by LaFeuilleMorte** [comment]
> > Hi @LaFeuilleMorte,
> > How big is your html file? Safari places limits on maximum size it will allow. If you can send us the file we can check this is the case.
> > If that is the issue we will release an update today which gives you the option of downloading a .zip file with external compressed.ply file. You must serve these files for it to work, but it doesn't have the same memory issue.
> > Thanks!
> 
> It's about 250 MB. That makes sense. In the previous versions. I exported html with no SH data. So the size would be only 65MB. But now it has SH data so it's much bigger and could possible cause this issue. I'll try smaller html with the same order of SH data to see if your conclusion is right.

Emm..., After some tests, I think this problem was caused by the size of the exported html. I got it worked at a much smaller size (50 MB).

**Comment by slimbuck** [comment]
BTW we've released an update to SuperSplat (v1.11.3) which supports .zip export of the html viewer.

The zip contains the HTML file and a separate compressed.ply model.

This version won't have the HTML size restriction, but it will require you run a server to access the files.
