### ISSUE TITLE
[Feature Request] PlayCanvas splat compression as a CLI tool

### ISSUE THREAD

**Issue by tonetechnician** [playcanvas/supersplat#355]
Hey @slimbuck 

I wondered whether it was on your roadmap to create a cli tool for playcanvas splat compression? 

I spent a little while yesterday trying to get this to work in node basing off the splat-serialize.ts. I reached a certain level where it was clear there is a dependency on a playcanvas app (and obviously dom browser) to be able to instantiate the splat entity first before being able to compress it. 

I wondered what you think it would take to create a cli tool that could handle the compression. I think this could be quite useful and offer a similar workflow to .spz compression whereby the compression can happen post training and pre-viewing. 

Would love to get your thoughts on this! Maybe I also missed something during my attempt at an implementation.

All the best

**Comment by slimbuck** [comment]
Hi @tonetechnician ,

I've thrown together a CLI tool for compressing gaussian splat ply files for you.

Please see https://github.com/playcanvas/splat-transform for npm install and usage instructions.

I've literally tested this code on 3 files, so please try it out first on files before committing to it and let me know.

I can imagine adding all sorts of interesting and useful processing options to this tool down the line (when we get time), hence the name for the package.

Thanks!

**Comment by slimbuck** [comment]
Closing this ticket. Please leave feedback on the CLI repo if you have any. Thanks!

**Comment by tonetechnician** [comment]
This is amazing @slimbuck, very keen to try this out! I agree, could definitely become a great way to process splats before viewing.
