### ISSUE TITLE
Add a View Cube to the viewport

### ISSUE THREAD

**Issue by CiberNin** [playcanvas/supersplat#40]
Implement something like https://fennec-hub.github.io/ThreeOrbitControlsGizmo/ so that the camera can be rotated or snapped to an axis while a selection tool is in use.

**Comment by slimbuck** [comment]
done in #64

**Comment by CiberNin** [comment]
It looks like you implemented gizmos for orienting a splat in the scene, which is a useful feature, but my issue was about implementing a gizmo in the top right to control the camera so you can snap to front-back-left-right-top-bottom and corners.
Another example than the one linked would be fusion 360:
![image](https://github.com/playcanvas/supersplat/assets/59232386/b919a68f-2585-4d66-9984-f3dd1225548e)

Being able to snap the camera to axis like this would make much easier to control point selections and align multiple splats.

**Comment by willeastcott** [comment]
Ah. So that gizmo is generally referred to as a ['View Cube'](https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-E6D3896C-AF39-4F5C-A57C-CACE2A1117F9). I have changed the title of this issue and reopened it.

**Comment by slimbuck** [comment]
Done in #135.
