### ISSUE TITLE
Filter region by base colour

### ISSUE THREAD

**Issue by pjbaron** [playcanvas/supersplat#46]
I'm finding that I often get a white fringe around the edge of the focus object - probably lifted from the walls or ceiling via a tracking inaccuracy.
To remove that kind of effect, it would be really helpful to be able to filter the currently selected dots by a colour range.
The dots would need to change colour as you adjust the colour range to show what will and won't be affected.

In the soft toy model, this feature would permit easy clean-up of all the white fuzz underneath (although I've just realised that may have been left there on purpose to indicate snow!)

https://playcanvas.com/viewer?default&debug.grid=false&cameraPosition=-1,1.1,-2.8&camera.multisample=false&camera.hq=false&ui.active=false&load=https://dl.dropboxusercontent.com/scl/fi/50sfqcl0a12dksq3szx6u/knitted-toy.ply?rlkey=euwuabnqmavtlcx37m99orpmv

White fringe along the top of a black T-Shirt:
![image](https://github.com/playcanvas/super-splat/assets/614817/7d2e8964-9bcf-4896-a1aa-d2c302227460)

**Comment by koktavy** [comment]
+1 for this feature. Selecting a color range, ideally with an adjustable tolerance, would help speed up the cleaning process.

**Comment by cangzihan** [comment]
I tried to modify the source code to add this function. Currently it can only be used to delete white Gaussian points(as in your image), I will continue to update it in the future. This is my repository https://github.com/cangzihan/super-splat.  

**You need to deploy it locally.** Then you will see that there is new button under `Delete Selected Splats`, and the usage is the same as this button.

**Comment by pjbaron** [comment]
Very cool, I will have a play with this soon!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by slimbuck** [comment]
Just want to point out that we have since added a histogram view in the new DATA panel (see #127).

With this, you can plot splats by hue/saturation/lightness and modify selection directly on the histogram (shift + drag to add, ctrl + drag to remove from selection).

It is pretty basic for color selection, because the colors aren't plotted in the histogram view, but you should still be able to do some of the filtering you describe.

**Comment by slimbuck** [comment]
Closing for now. SPLAT DATA panel can help with this, though we will be adding more sophisticated controls at some point.
