### ISSUE TITLE
Apply new limits to the splat min/max

### ISSUE THREAD

**Issue by pjbaron** [playcanvas/supersplat#49]
For the giant splats that stick out from surfaces and edges, a useful option would be the ability to apply local limits on the min/max size of each splat.  Some of the splats generated by Poly.cam are incredibly large (10cm or more), which will be very efficient when they're orientated correctly, but is a major hassle when they are not.
This suggestion is to add some edit boxes/sliders showing the current min/max limits in use, and the ability to adjust them for the current selection. This would probably cross over with another suggestion about rescaling the model.
https://github.com/playcanvas/super-splat/pull/31

**Comment by slimbuck** [comment]
This is largely possible using the SPLAT DATA histogram panel and transform tools.
