### ISSUE TITLE
merge two gaussian splatting scene

### ISSUE THREAD

**Issue by amberhappy** [playcanvas/supersplat#53]
Hi, I have question about how to merge two gaussian splatting scene? when I load two scene into super-splat, they are sperated to differnt coordinate(cannot merge), and cannot be export to one ply.

**Comment by slimbuck** [comment]
Hi @amberhappy, unfortunately you can't combine splats right now. To support this we'd probably have to add gizmos for being able to place/orientate each splat. This is also on the todo list!

**Comment by Maxiviper117** [comment]
Such a feature would be very useful, doing this with the unity plugin is overly long-winded

**Comment by slimbuck** [comment]
This was done in #105 and is now deployed.
