### ISSUE TITLE
Position Rotation Scale - missing SCENE tab

### ISSUE THREAD

**Issue by arlo-ml** [playcanvas/supersplat#70]
hi,
is there a reason why with the new version we can't rotate the file inserting the values in the SCENE tab?
sometimes you just need to rotate 90 degrees, and you can't have a good control using transform gizmos 

![supersplat](https://github.com/playcanvas/super-splat/assets/63562596/1eee99a4-ce4a-4fb0-9e59-f005dac362a1)

**Comment by showpixelVR** [comment]
> hi, is there a reason why with the new version we can't rotate the file inserting the values in the SCENE tab? sometimes you just need to rotate 90 degrees, and you can't have a good control using transform gizmos
> 
> ![supersplat](https://private-user-images.githubusercontent.com/63562596/305165008-1eee99a4-ce4a-4fb0-9e59-f005dac362a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODg2MjksIm5iZiI6MTcxMTE4ODMyOSwicGF0aCI6Ii82MzU2MjU5Ni8zMDUxNjUwMDgtMWVlZTk5YTQtY2U0YS00ZmIwLTllNTktZjAwNWRhYzM2MmExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDEwMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMGU1MDg2MzI3NDUyNzM5N2QxZGRkMjhhOTJjZjVhMjBmNzU0YmQxOWZkMThlN2JhNjNiZDZhYTRkYTI2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32vusOQFelGidPgK6gPCic8X43eM5GOZ92Bg9su5RXg)

I had the same thougts.
