### ISSUE TITLE
Spherical Harmonics

### ISSUE THREAD

**Issue by PLAN8VR** [playcanvas/supersplat#87]
Has the option for importing Spherical Harmonics been removed? I can see the option available in v 0.10.3 from one of the screenshots, but it appears to have been removed since then?

"IMPORTANT NOTE

the editor viewport does not render the spherical harmonic lighting data (please submit issue if you'd like this to be added)"

 .... YES PLEASE!!!!

**Comment by willeastcott** [comment]
I believe `OPTIONS -> Load all PLY data` controls whether spherical harmonics data is loaded.

**Comment by PLAN8VR** [comment]
> I believe `OPTIONS -> Load all PLY data` controls whether spherical harmonics data is loaded.

Ahh, thanks for the tip!
