### ISSUE TITLE
Update PWA Manifest to indicate supported file types

### ISSUE THREAD

**Issue by CiberNin** [playcanvas/supersplat#91]
Need to add something like this so that once the PWA is installed it will be offered as an option when selecting default file opener.
```json
"file_handlers": [
    {
      "action": "/",
      "accept": {
        "model/splat": [".splat"],
        "model/ply": [".ply"]
      }
    }
  ]
```

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Associate_files_with_your_PWA

**Comment by willeastcott** [comment]
Oh, that's really cool. I didn't know that was possible. Did you want to add this @CiberNin, or should I?

**Comment by CiberNin** [comment]
Can you do it, I was a bit confused by the part about handling files from a launch queue. It also might be nice to look into if you can get it working with just a standard file save dialog instead of downloading. Which seems like something that the PWA filesystem api would permit.

**Comment by marklundin** [comment]
Might want to add share targets too https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target#browser_compatibility

**Comment by slimbuck** [comment]
> Can you do it, I was a bit confused by the part about handling files from a launch queue. It also might be nice to look into if you can get it working with just a standard file save dialog instead of downloading. Which seems like something that the PWA filesystem api would permit.

Standard save dialog would be really great.

**Comment by willeastcott** [comment]
@CiberNin This is now deployed. Try it out - hopefully you approve. 😄
