### ISSUE TITLE
Stray Splat in 0.17.2

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/supersplat#96]
This should illustrate the problem (splat on tail):

https://github.com/playcanvas/supersplat/assets/697563/07596ec6-db86-4294-b62b-312f2ac9faba

I realize that this is an engine bug, but I'm logging this here since other SuperSplat users are likely to encounter this.

PLY is here:

https://github.com/willeastcott/assets/blob/main/dragon.compressed.ply

**Comment by slimbuck** [comment]
Scratch that, repro'd.
